### ISSUE TITLE
[Test-Proxy] Propagate more detail for proxy exceptions

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#2308]
When using an old endpoint in Record mode, I just get back a 500 from the test proxy. I can see in the proxy error output, that there was an HttpRequestException - No such host is known.
Can we include this exception in the response?

```
      Connection id "0HMDA5RCFFRRC", Request id "0HMDA5RCFFRRC:00000002": An unhandled exception was thrown by the application.
      System.Net.Http.HttpRequestException: No such host is known. (joloveventgridcloudevent-topic.westus2-1.eventgrid.azure.net:443)
       ---> System.Net.Sockets.SocketException (11001): No such host is known.
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
```

**Comment by JoshLove-msft** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-tools/issues/2328
