### ISSUE TITLE
[TestProxy] Exception when reading streams

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-tools#2385]
Issue: there is an uncaught exception when reading what looks like empty streams
```bash
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidCastException: Unable to cast object of type 'System.Net.Http.EmptyReadStream' to type 'System.IO.MemoryStream'.
         at Azure.Sdk.Tools.TestProxy.RecordingHandler.HandleRecordRequest(String recordingId, HttpRequest incomingRequest, HttpResponse outgoingResponse, HttpClient client) in /proxyservercode/RecordingHandler.cs:line 147
         at Azure.Sdk.Tools.TestProxy.Record.HandleRequest() in /proxyservercode/Record.cs:line 54
         at lambda_method7(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

How to reproduce:
* checkout the branch of azure-sdk-for-go at `seankane-msft/storage-recordings`
* Run `go test -v -run TestBlobStartCopyDestIfModifiedSinceTrue`

**Comment by seankane-msft** [comment]
I believe this occurs at any `BlockBlobClient.GetProperties` call

**Comment by scbedd** [comment]
Hey @seankane-msft ?

I checked out the branch, and set environment variables for:

```
$env:PROXY_CERT="<pathtoproxycert>"
$env:AZURE_RECORD_MODE="playback"
go test -v -run TestBlobStartCopyDestIfModifiedSinceTrue
=== RUN   TestBlobStartCopyDestIfModifiedSinceTrue
    proxy_test.go:50:
                Error Trace:    proxy_test.go:50
                                                        zt_blob_client_test.go:729
                Error:          Received unexpected error:
                                decode account key: illegal base64 data at input byte 12
                Test:           TestBlobStartCopyDestIfModifiedSinceTrue
--- FAIL: TestBlobStartCopyDestIfModifiedSinceTrue (0.24s)
```
