### ISSUE TITLE
[Test-Proxy] InternalServerError in playback CI - Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-tools#2451]
Seeing this error in the test proxy logs when running tests which do paged responses: 

"System.InvalidOperationException: Collection was modified; enumeration operation may not execute."

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1325483&view=logs&j=f8949c67-9d21-53bc-b8db-079dc324f468&t=51108116-18f2-5b30-589b-19b2eea88829&l=2304

Example recording of a test which failed: https://github.com/Azure/azure-sdk-for-python/blob/21f24f8b4546bbd82f93aa3d88be79fb5a9c8f60/sdk/translation/azure-ai-translation-document/tests/recordings/test_list_translations.pyTestListTranslationstest_list_translations_with_pagination.json#L2151

It seems random which `list_` tests will fail upon re-run of the pipeline. I haven't been able to reproduce this locally - everything runs successfully in playback on my pc. 

Docker image tag: 1209124, 1251067, 1294199 or 1314089

**Comment by scbedd** [comment]
Tracked this down! Thankfully, the test-proxy is NOT handling these parallel requests wrong! 

After adding a bunch of debugging information (I will be merging some additional loggin as an improvement), we have an 
answer as to what is happening. The problem, lies with these requests in the [additional-logging-build failures](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1331536&view=logs&j=29cbd47f-5b04-5aae-27ea-c5db931f8609&t=6f4236c0-e0ce-5979-2129-59b4ad74eed4&l=5807). Pulling the logging failure out.

```
  at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
     at Azure.Sdk.Tools.TestProxy.Common.RecordSession.Lookup(RecordEntry requestEntry, RecordMatcher matcher, IEnumerable`1 sanitizers, Boolean remove) in /mnt/vss/_work/1/s/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordSession.cs:line 87
     at Azure.Sdk.Tools.TestProxy.RecordingHandler.HandlePlaybackRequest(String recordingId, HttpRequest incomingRequest, HttpResponse outgoingResponse) in /mnt/vss/_work/1/s/tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs:line 344
     at Azure.Sdk.Tools.TestProxy.Playback.HandleRequest() in /mnt/vss/_work/1/s/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Playback.cs:line 53
     at lambda_method29(Closure , Object )
     at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
  --- End of stack trace from previous location ---
     at Microsoft.AspNetCore.Mvc.Infrastructure.Resour  
```

Yep, that looks wrong! That's [this location](https://github.com/Azure/azure-sdk-tools/blob/f09bc139d48cb6b073d94500f361c491bd1a11ab/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordSession.cs#L87) in code. Why are the **session sanitizers** changing while recordings are actually playing back!? 

Combined with the addition of `sending sanitizer` logging, we can see that [we're setting WAY more session level](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1331536&view=logs&j=f8949c67-9d21-53bc-b8db-079dc324f468&t=51108116-18f2-5b30-589b-19b2eea88829&l=1906) sanitizers than we expect.

This is because we were _adding sanitizers_ while tests were _running_. 

I should add error handling to catch this _exact_ scenario and be explicit about what the error is. However, I do not believe that I will be adding a global lock on `Sanitizers` list server side. I believe that this turned up a behavior that we weren't aware of python side, and it's valuable to KNOW that sanitizers are being added _during_ a playback or record session.

I believe we should update [this function](https://github.com/Azure/azure-sdk-for-python/blob/c060fc34dd996622575e2107ebec76e99bbd9868/tools/azure-sdk-tools/devtools_testutils/azure_recorded_testcase.py#L36) to only apply recording level sanitizers. @mccoyp lets chat in the morning and figure it out!
