### ISSUE TITLE
[Test Proxy] Request is not matched in playback - (likely) because of the unicode encoding

### ISSUE THREAD

**Issue by HarshaNalluru** [Azure/azure-sdk-tools#2723]
Commit that repros - [5bdeaec](https://github.com/Azure/azure-sdk-for-js/pull/20264/commits/5bdeaec0b0391ed05f87d6e9ff36be1d8c5b1882)

```
// Differences
request: \u0022%PDF-1.7\r%\uFFFD\uFFFD\uFFFD\uFFFD\r\n81 0 obj\r\u003C\u003C/Li\u0022\n     
record:  \u0022%PDF-1.7\r%\uFFFD\uFFFD\uFFFD\uFFFD\r\n81 0 o\u0022\n"
```

```sh
[node-tests] 
[node-tests]   1) [AAD] analysis (Node)
[node-tests]        content analysis
[node-tests]          pdf file stream:
[node-tests]      RestError: {"Message":"Unable to find a record for the request POST https://endpoint/formrecognizer/documentModels/prebuilt-layout:analyze?api-version=2022-01-30-preview\nHeader differences:\nBody differences:\nRequest and response bodies do not match at index 10:\n     request: \u0022%PDF-1.7\r%\uFFFD\uFFFD\uFFFD\uFFFD\r\n81 0 obj\r\u003C\u003C/Li\u0022\n     record:  \u0022%PDF-1.7\r%\uFFFD\uFFFD\uFFFD\uFFFD\r\n81 0 o\u0022\n","Status":"NotFound"}
[node-tests]       at handleErrorResponse (/workspaces/azure-sdk-for-js/sdk/core/core-client/src/deserializationPolicy.ts:251:17)
[node-tests]       at deserializeResponseBody (/workspaces/azure-sdk-for-js/sdk/core/core-client/src/deserializationPolicy.ts:159:43)
[node-tests]       at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

For now, unblocked my builds with the bodilessmatcher.

**Comment by scbedd** [comment]
@HarshaNalluru Confirming before I try.

Remove [this line](https://github.com/Azure/azure-sdk-for-js/blob/862339f888c3e8895abac00a796146f50fd3268e/sdk/formrecognizer/ai-form-recognizer/test/public/node/analysis.spec.ts#L50).
Go after [this test](https://github.com/Azure/azure-sdk-for-js/blob/862339f888c3e8895abac00a796146f50fd3268e/sdk/formrecognizer/ai-form-recognizer/test/public/node/analysis.spec.ts#L543)

Should repro in playback.

**Comment by HarshaNalluru** [comment]
Yes @scbedd :)
