### ISSUE TITLE
doc-warden doesn't support utf8

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-tools#282]
Repro: put ❗ into the readme.

```
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\Scripts\ward.exe\__main__.py", line 9, in <module>
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\warden\cmd_entry.py", line 27, in console_entry_point
    command_selector.get(cfg.command)(cfg)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\warden\cmd_entry.py", line 88, in all_operations
    content_results, ignored_content_results = verify_readme_content(config)
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\warden\enforce_readme_content.py", line 33, in verify_readme_content
    readme_results.append(verify_md_readme(readme, config, section_sorting_dict))
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\site-packages\warden\enforce_readme_content.py", line 59, in verify_md_readme
    readme_content = f.read()
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1662: character maps to <undefined>

```

cc @scbedd

**Comment by scbedd** [comment]
Thankfully the solution here is to simply release the latest version to pypi. Thanks for the callout @pakrym 

PR that addressed this problem: #237 

Leverage version `0.3.1` from [pypi](https://pypi.org/project/doc-warden/) that I just released.

**Comment by scbedd** [comment]
I'm closing this issue, I tried your repro case to success. Feel free to scream at me if you `pip install doc-warden --upgrade` and it doesn't work. I'm fairly confident you should be good.

**Comment by pakrym** [comment]
It fails in CI

**Comment by scbedd** [comment]
Can you ping me the pipeline? It's possible the pipeline is referencing a specific version of doc-warden that I need to update.

**Comment by pakrym** [comment]
Added to the comment

**Comment by scbedd** [comment]
Yeah ok:

![image](https://user-images.githubusercontent.com/45376673/68330403-0bb22d00-0088-11ea-9192-e029b1a2b74b.png)

Gimme a sec to check the pipeline def specifically.

**Comment by scbedd** [comment]
@pakrym I thought that was a new build. I _just_ released the version of doc-warden, so any SUCCESSIVE builds will succeed on this now. This was absolutely broken on your PR. My claim is that any NEW PRs that run this code should be good to go.

**Comment by pakrym** [comment]
Sounds good.
