### ISSUE TITLE
Failing PR check in azure-rest-api-specs

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#2882]
The "Breaking Change" PR check in https://github.com/Azure/azure-rest-api-specs/pull/17439 is failing with a script error:
```
Processing swaggers:
[
  'specification/common-types/resource-management/v4/privatelinks.json',
  'specification/iotcentral/resource-manager/Microsoft.IoTCentral/preview/2021-11-01-preview/iotcentral.json'
]
TypeError: Cannot read property 'createdSwaggers' of undefined
    at createDummySwagger (/home/vsts/work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.26/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:429293:10)
    at Object.<anonymous> (/home/vsts/work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.26/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:429389:37)
    at step (/home/vsts/work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.26/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:428518:23)
    at Object.next (/home/vsts/work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.26/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:428499:53)
    at fulfilled (/home/vsts/work/_tasks/AzureApiValidation_5654d05d-82c1-48da-ad8f-161b817f6d41/0.0.26/private/azure-swagger-validation/azureSwaggerValidation/dist/main.js:428490:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by weshaggard** [comment]
@akning-ms who is the owner for this tool?

**Comment by akning-ms** [comment]
This issue looks has been fixed by @jianyexi in one of this week's release.  @mikekistler  to confirm and close the issue

**Comment by mikekistler** [comment]
Does appear to be fixed.  Thank you!
