### ISSUE TITLE
SDK Automation checks fail to complete if there is a bad readme

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#3013]
Example see https://github.com/Azure/azure-rest-api-specs/pull/18465 or the jobs at https://dev.azure.com/azure-sdk//internal/_build/results?buildId=1468888&view=logs&j=93811faa-026e-5426-72ec-2dc2b400fa28

```
Begin compare specification/cognitiveservices/data-plane/Language/readme.md : release_2022_03_01_preview
TypeError: Cannot read property 'startsWith' of undefined
    at Object.ResolveUri (/home/vsts/.autorest/@autorest_core@3.0.6375/node_modules/@autorest/core/dist/vendors-common_temp_node_modules_pnpm_azure-tools_eventing_3_0_252_node_modules_azure-tools_e-1bb884.js:2247:19)
    at Object.getBaseFolderUri (/home/vsts/.autorest/@autorest_core@3.0.6375/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:417:89)
##[error]Fatal error: {}
    at createConfigFromRawConfig (/home/vsts/.autorest/@autorest_core@3.0.6375/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:374:35)
    at Object.extendAutorestConfiguration (/home/vsts/.autorest/@autorest_core@3.0.6375/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:395:23)
    at AutorestContext.extendWith (/home/vsts/.autorest/@autorest_core@3.0.6375/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:661:55)
    at AutorestContext.getNestedConfiguration (/home/vsts/.autorest/@autorest_core@3.0.6375/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:652:28)
    at getNestedConfiguration.next (<anonymous>)
    at resolveExtensions (/home/vsts/.autorest/@autorest_core@3.0.6375/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:1275:67)
    at async ConfigurationLoader.CreateView (/home/vsts/.autorest/@autorest_core@3.0.6375/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:1379:13)
    at async AutoRest.RegenerateView (/home/vsts/.autorest/@autorest_core@3.0.6375/node_modules/@autorest/core/dist/src_lib_autorest-core_ts.js:94:30)
```
Failures of those types seem to cause the After step to fail as well and github bot doesn't seem to update the status check on the PR and so it remains in a pending state.

**Comment by akning-ms** [comment]
This should be fixed in recently release @jianyexi to confirm

**Comment by jianyexi** [comment]
yes, fixed this case

**Comment by weshaggard** [comment]
@jianyexi could you please link to the code change that fixed this issue and then you can close this PR.

**Comment by jianyexi** [comment]
my fix is in devops Repo , is it appropriate to put it here
