### ISSUE TITLE
[ApiView]Swagger apiParser support operation level parameter schema

### ISSUE THREAD

**Issue by ruowan** [Azure/azure-sdk-tools#4716]
In swagger operation model, we defined method model.  We need to support parameter model in operation level. Otherwise, the JsonSerializer failed.

specification/digitaltwins/data-plane/Microsoft.DigitalTwins/stable/2022-05-31/digitaltwins.json

from this PR

https://github.com/Azure/azure-rest-api-specs-pr/pull/9407

Error message: 
```
Generating codefile for swagger file: digitaltwins.swagger
Unhandled exception: System.Text.Json.JsonException: The JSON value could not be converted to SwaggerApiParser.Operation. Path: $.paths['/models'].parameters | LineNumber: 19 | BytePositionInLine: 21.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at SwaggerApiParser.SwaggerDeserializer.Deserialize(String swaggerFilePath) in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerDeserializer.cs:line 13
   at SwaggerApiParser.SwaggerDeserializer.Deserialize(String swaggerFilePath) in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerDeserializer.cs:line 14

```

**Comment by ruowan** [comment]
PR created. https://github.com/Azure/azure-sdk-tools/pull/4740

**Comment by ruowan** [comment]
Fixed and close this issue
