### ISSUE TITLE
tox-monorepo not compatible with Tox 4

### ISSUE THREAD

**Issue by sebastian-philipp** [Azure/azure-sdk-tools#4917]
Hi there, 

```
ROOT: 141 D setup logging to DEBUG on pid 18 [tox/report.py:241]
Traceback (most recent call last):
  File "/usr/local/bin/tox", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.10/site-packages/tox/run.py", line 19, in run
    result = main(sys.argv[1:] if args is None else args)
  File "/usr/local/lib/python3.10/site-packages/tox/run.py", line 38, in main
    state = setup_state(args)
  File "/usr/local/lib/python3.10/site-packages/tox/run.py", line 53, in setup_state
    options = get_options(*args)
  File "/usr/local/lib/python3.10/site-packages/tox/config/cli/parse.py", line 38, in get_options
    guess_verbosity, log_handler, source = _get_base(args)
  File "/usr/local/lib/python3.10/site-packages/tox/config/cli/parse.py", line 61, in _get_base
    MANAGER.load_plugins(source.path)
  File "/usr/local/lib/python3.10/site-packages/tox/plugin/manager.py", line 83, in load_plugins
    self._register_plugins(inline)
  File "/usr/local/lib/python3.10/site-packages/tox/plugin/manager.py", line 37, in _register_plugins
    self.manager.load_setuptools_entrypoints(NAME)
  File "/usr/local/lib/python3.10/site-packages/pluggy/_manager.py", line 287, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line [68](https://gitlab.com/.../-/jobs/3443752893#L68)8, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 8[83](https://gitlab.com/.../-/jobs/3443752893#L83), in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/tox_monorepo/__init__.py", line 8, in <module>
    from .monorepo import *
  File "/usr/local/lib/python3.10/site-packages/tox_monorepo/monorepo.py", line 5, in <module>
    from tox.reporter import verbosity0
ModuleNotFoundError: No module named 'tox.reporter'
```

If we need to do some manual upgrade steps, it would be great to have this in the README

Thank you!

**Comment by cpapazaf** [comment]
Hi,

This breaks tox-monorepo.

Intermediate fix for anyone facing the problem:

```bash
$cat <<EOF > constraints.txt
tox==3.27.1
EOF
$pip install -c constraints.txt tox-monorepo
```

**Comment by kurtzeborn** [comment]
@sebastian-philipp and/or @cpapazaf, if either of you would like to create a PR with your suggested fix, we'd be happy to review it.  Otherwise, we'll take a look at it when it comes up on our backlog.

**Comment by sebastian-philipp** [comment]
don't know when we'll have the time to work on it. Might depend on when something makes me want to upgrade to tox4.

**Comment by tchia04** [comment]
Should this issue be resolved now after the completion of https://github.com/Azure/azure-sdk-for-python/pull/30159 ?

**Comment by sebastian-philipp** [comment]
@tchia04 
![image](https://github.com/Azure/azure-sdk-tools/assets/2574405/f6ff0e49-aaf8-444c-87c2-ea735011ff80)

Seems we no longer need this for tox4 at all?

**Comment by scbedd** [comment]
> @tchia04 ![image](https://private-user-images.githubusercontent.com/2574405/306697139-f6ff0e49-aaf8-444c-87c2-ea735011ff80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NjE5MDIsIm5iZiI6MTcwODU2MTYwMiwicGF0aCI6Ii8yNTc0NDA1LzMwNjY5NzEzOS1mNmZmMGU0OS1hYWY4LTQ0NGMtODdjMi1lYTczNTAxMWZmODAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMDAyNjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTcyMDUxNzY1MWM0OWY1YmFkZmZjN2RmOThjNGE5ZTEzNTk3YThiYTMyZTIxM2IyMjliNmIxMDkxMzdhOWQzMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xWx52-KcG60VXa-MnxytOA3EAWt_brvj5cJvCeyoyjE)
> 
> Seems we no longer need this for tox4 at all?

Agreed. `tox-monorepo` was entirely supplanted by the `--root` argument addition to `tox 4`. I'm going to close this issue out and add an upper bound to `tox-monorepo` before marking the package as deprecated. Folks should definitely be using `tox 4` and `tox-monorepo` is useless on that version!
