### ISSUE TITLE
"automation - build-failure-notification-subscriptions" pipeline fails on unsupported team name

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#4925]
## The problem

The [internal / automation - build-failure-notification-subscriptions (Microsoft-internal)](https://dev.azure.com/azure-sdk/internal/_build?definitionId=679&_a=summary) pipeline [is failing on the `Run Team/Notification Creator` step with the following error](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2042219&view=logs&j=1f7b91b6-9a2a-5c83-7d3e-ca0fa5848c83&t=cdd04468-e304-5da0-e0b2-ea410a114c81&l=7961y):

```
info: Azure.Sdk.Tools.NotificationConfiguration.Services.AzureDevOpsService[0]
      => Evaluate Pipeline: Name = (2022-12-08 02:55:47) java - jdbc - tests, Path = \java, Id = <ID>
      UpdateTeamForProjectAsync TeamName = <ID> (2022-12-08 02:55:47) java - jdbc - tests ProjectId = <ID>
Unhandled exception: Microsoft.TeamFoundation.Core.WebApi.InvalidTeamNameException: TF400472: The following team name is not valid: <ID> (2022-12-08 02:55:47) java - jdbc - tests. Verify that the name does not exceed the maximum character limit, only contains valid characters, and is not a reserved name.  The following characters are not valid: @ ~ ;  ' + = , < > | / \ ? : & $ * " # [ ]
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Azure.Sdk.Tools.NotificationConfiguration.Services.AzureDevOpsService.UpdateTeamForProjectAsync(String projectId, WebApiTeam team) in /mnt/vss/_work/1/s/tools/identity-resolution/Services/AzureDevOpsService.cs:line 183
   at Azure.Sdk.Tools.NotificationConfiguration.NotificationConfigurator.EnsureTeamExists(BuildDefinition pipeline, TeamPurpose purpose, IEnumerable`1 teams, GitHubToAADConverter gitHubToAADConverter, Boolean persistChanges) in /mnt/vss/_work/1/s/tools/notification-configuration/notification-creator/NotificationConfigurator.cs:line 177
   at Azure.Sdk.Tools.NotificationConfiguration.NotificationConfigurator.ConfigureNotifications(String projectName, String projectPath, GitHubToAADConverter gitHubToAADConverter, Boolean persistChanges, PipelineSelectionStrategy strategy) in /mnt/vss/_work/1/s/tools/notification-configuration/notification-creator/NotificationConfigurator.cs:line 55
   at Azure.Sdk.Tools.NotificationConfiguration.Program.Main(String organization, String project, String pathPrefix, String tokenVariableName, String aadAppIdVar, String aadAppSecretVar, String aadTenantVar, PipelineSelectionStrategy selectionStrategy, Boolean dryRun) in /mnt/vss/_work/1/s/tools/notification-configuration/notification-creator/Program.cs:line 63
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass2_0.<<InvokeAsync>b__0>d.MoveNext()
```

## Proposed fixes

To address the issue, all of the following is to be done:

- Fix the logic in `NotificationConfigurator` to properly sanitize pipeline names when converting them to team names;
- Even when escaping will work, get rid or rename the offending pipelines: [
(2022-12-08 02:55:47) java - jdbc - tests](https://dev.azure.com/azure-sdk/internal/_build?definitionId=5647) and [(2022-12-08 02:55:49) java - jdbc - tests-weekly](https://dev.azure.com/azure-sdk/internal/_build?definitionId=5648). Note that these pipelines are sourced from `tests.yml`, which is no longer available, as it was recently moved, [as seen in this PR](https://github.com/Azure/azure-sdk-for-java/commit/dc6b7d5805fabfa9bb50092be215b9eb60ff2aaa#diff-d6b1ffe0177f3e45a9e8be3c4fb7ff71149bb61121ce7798e647e128b5a3a5f0).

**Comment by konrad-jamrozik** [comment]
@saragluna can the two pipelines [mentioned above](https://github.com/Azure/azure-sdk-tools/issues/4925) be removed? They seem to be no longer valid, since you moved the `test.yml` in PR https://github.com/Azure/azure-sdk-for-java/pull/32437

**Comment by konrad-jamrozik** [comment]
I renamed the pipelines by replacing `:` with `_`. It [unblocked the pipelines](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2042219&view=logs&j=4408bae3-6c11-523f-d40f-7b52954218c8&t=b85739d7-d665-5b84-6fdc-ca8309228ba6). @weshaggard FYI.

**Comment by saragluna** [comment]
> @saragluna can the two pipelines [mentioned above](https://github.com/Azure/azure-sdk-tools/issues/4925) be removed? They seem to be no longer valid, since you moved the `tests.yml` in PR [Azure/azure-sdk-for-java#32437](https://github.com/Azure/azure-sdk-for-java/pull/32437)

The tests.yml has been removed, and yesterday I deleted these two pipelines. But then I thought simply deleting them would make some pipeline links shared in email or GitHub invalid, so I restored these pipelines. The names were generated automatically. Sorry for breaking other jobs or pipelines. I have changed the pipeline names and disabled them.
