### ISSUE TITLE
Swagger API review - Failed to deserialize swagger JSON

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5302]
Swagger API review gen failed to deserialize swagger JSON file in PR https://github.com/Azure/azure-rest-api-specs-pr/pull/10159

Unhandled exception: System.Text.Json.JsonException: 's' is invalid after a single JSON value. Expected end of data. Path: $ | LineNumber: 2671 | BytePositionInLine: 1.
 ---> System.Text.Json.JsonReaderException: 's' is invalid after a single JSON value. Expected end of data. LineNumber: 2671 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at SwaggerApiParser.SwaggerDeserializer.Deserialize(String swaggerFilePath) in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerDeserializer.cs:line 13

**Comment by ruowan** [comment]
That's a syntax issue in swagger file. Pls check that file again. I have test it with swagger file from the PR. I could generate it locally.

**Comment by praveenkuttappan** [comment]
@ruowan Did this file get flagged by any other checks in spec PR pipeline if file syntax is incorrect?

**Comment by maririos** [comment]
If the file from the PR is fine and the error was in the manual upload it could have been me on how I created the review. I suggest closing the issue and if it happens again reopen
