### ISSUE TITLE
[Prioritized] Retry all git commands (aside from internal mechanisms)

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#5660]
Specifically in the case of a **timeout**, not other command errors. Is there any way to verify that exit code?

**Comment by scbedd** [comment]
What this looks like in log:

```bash
2023-03-08T20:08:36.6127360Z ========================== Starting Command Output ===========================
2023-03-08T20:08:36.6165040Z [command]/usr/local/bin/pwsh -NoLogo -NoProfile -NonInteractive -Command . '/Users/runner/work/_temp/eb6b21ee-5314-44bf-9a9b-f90564d6af6a.ps1'
2023-03-08T20:08:37.1478840Z git --version
2023-03-08T20:08:37.2786400Z git remote -v
2023-03-08T20:08:37.2979630Z git clone -c core.longpaths=true --no-checkout --filter=tree:0 [https://github.com/Azure/azure-sdk-assets](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-assets&data=05%7C01%7Cscbedd%40microsoft.com%7C6fbdcd3242ef4ee4e2e608db201d51ae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638139082529505728%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=D2L5lcciGUtHx7HmcIRrkLdyzbTGSZJL2rY78TmeUvo%3D&reserved=0) .
2023-03-08T20:08:45.3768300Z Unhandled exception. Azure.Sdk.Tools.TestProxy.Common.Exceptions.HttpException: Invocation of "git clone -c core.longpaths=true --no-checkout --filter=tree:0 [https://github.com/Azure/azure-sdk-assets](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-assets&data=05%7C01%7Cscbedd%40microsoft.com%7C6fbdcd3242ef4ee4e2e608db201d51ae%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638139082529661908%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9TDuGnA2Gi3G3NKHHUk2CErs%2FEbywT8eBkeeecSGc64%3D&reserved=0) ." had a non-zero exit code -1.
2023-03-08T20:08:45.3779650Z StdOut:
2023-03-08T20:08:45.3782290Z StdErr: Cloning into '.'...
2023-03-08T20:08:45.3784360Z fatal: unable to access 'https://github.com/Azure/azure-sdk-assets/': Failed to connect to github.com port 443: Operation timed out
2023-03-08T20:08:45.3785680Z
2023-03-08T20:08:45.3786200Z
2023-03-08T20:08:45.3788770Z    at Azure.Sdk.Tools.TestProxy.Store.GitStore.InitializeAssetsRepo(GitAssetsConfiguration config, Boolean forceInit) in /mnt/vss/_work/1/s/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs:line 456
2023-03-08T20:08:45.3791720Z    at Azure.Sdk.Tools.TestProxy.Store.GitStore.Restore(String pathToAssetsJson) in /mnt/vss/_work/1/s/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs:line 152
2023-03-08T20:08:45.3794070Z    at Azure.Sdk.Tools.TestProxy.Startup.Run(Object commandObj) in /mnt/vss/_work/1/s/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs:line 154
2023-03-08T20:08:45.3795680Z    at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
2023-03-08T20:08:45.3797700Z    at Azure.Sdk.Tools.TestProxy.Startup.Main(String[] args) in /mnt/vss/_work/1/s/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Startup.cs:line 67
2023-03-08T20:08:45.3799200Z    at Azure.Sdk.Tools.TestProxy.Startup.<Main>(String[] args)
2023-03-08T20:08:45.7767260Z ##[error]PowerShell exited with code '1'.
2023-03-08T20:08:45.7791310Z ##[section]Finishing: Restore Recordings
```

**Comment by scbedd** [comment]
Occurrence information:

[Data Source](https://dataexplorer.azure.com/clusters/azsdkengsys.westus2/databases/Pipelines?query=H4sIAAAAAAAAA8WQT0vDQBDF736KIZem0HbVY6EWqwiB+ufgXSa702Q12Q07s4qhH95spEXqVfAyMPNm3vsxm2gbs/XV1jo628NHTYHg2bbEgm0HV4CVzy8uz830qN4TM1YENTJkOxRslhAdlg2BeECtBx0mtUjHS6UqK3UsF9q36rqPgRSmOmfzNkdmElaTbLDm2LYYbE9w46OTOx82ieyWdtZZsd6tdJrnUyg/DwQzON1hCRolzw7hht4XY96Yn83gMVTobI9p+wHbwSJL46fgX0lLYVL/UibXtTnaFmaV/coqho8otYfu+/SE6S9JVCCOjfB67H7ADAj//YIvEQCY1D8CAAA=)

```kusto
BuildLogLine
| where Timestamp > ago(120d)
| where Message has "fatal: unable to access 'https://github.com/Azure/azure-sdk-assets/'"
| summarize CountForBuildDefinition=count() by Message, BuildDefinition=strcat("https://dev.azure.com/", OrganizationName, "/", ProjectId, "/_build?definitionId=", BuildDefinitionId)
//| project Message, Build=strcat("https://dev.azure.com/", OrganizationName, "/", ProjectId, "/_build/results?buildId=", BuildId), BuildDefinition=strcat("https://dev.azure.com/", OrganizationName, "/", ProjectId, "/_build?definitionId=", BuildDefinitionId)
```
