### ISSUE TITLE
[TypeSpec APIView] fails for enums that contain spreads

### ISSUE THREAD

**Issue by serbrech** [Azure/azure-sdk-tools#5664]
`tsp compile . --options arm-types-path=../../../../../../common-types/resource-management`

```
TypeSpec compiler v0.41.0
ExternalError: Emitter "@azure-tools/typespec-apiview" failed!
File issue at https://github.com/Azure/azure-sdk-tools/issues
Error: Unable to get name for node.
    at ApiView.getNameForNode (file:///home/stephane/code/aks-rp/swagger/containerservice/fleets.management/node_modules/@azure-tools/typespec-apiview/dist/src/apiview.js:878:19)
    at ApiView.tokenizeEnumStatement (file:///home/stephane/code/aks-rp/swagger/containerservice/fleets.management/node_modules/@azure-tools/typespec-apiview/dist/src/apiview.js:570:37)
    at ApiView.tokenize (file:///home/stephane/code/aks-rp/swagger/containerservice/fleets.management/node_modules/@azure-tools/typespec-apiview/dist/src/apiview.js:354:22)
    at ApiView.tokenizeNamespaceModel (file:///home/stephane/code/aks-rp/swagger/containerservice/fleets.management/node_modules/@azure-tools/typespec-apiview/dist/src/apiview.js:732:18)
    at ApiView.emit (file:///home/stephane/code/aks-rp/swagger/containerservice/fleets.management/node_modules/@azure-tools/typespec-apiview/dist/src/apiview.js:248:22)
    at Object.emitApiView (file:///home/stephane/code/aks-rp/swagger/containerservice/fleets.management/node_modules/@azure-tools/typespec-apiview/dist/src/emitter.js:159:21)
    at Object.$onEmit [as emitFunction] (file:///home/stephane/code/aks-rp/swagger/containerservice/fleets.management/node_modules/@azure-tools/typespec-apiview/dist/src/emitter.js:9:19)
    at runEmitter (file:///home/stephane/code/aks-rp/swagger/containerservice/fleets.management/node_modules/@typespec/compiler/dist/core/program.js:526:27)
    at compile (file:///home/stephane/code/aks-rp/swagger/containerservice/fleets.management/node_modules/@typespec/compiler/dist/core/program.js:238:15)
    at async Object.handler (file:///home/stephane/code/aks-rp/swagger/containerservice/fleets.management/node_modules/@typespec/compiler/dist/core/cli/cli.js:114:25)
    at runEmitter (file:///home/stephane/code/aks-rp/swagger/containerservice/fleets.management/node_modules/@typespec/compiler/dist/core/program.js:543:19)
    at async compile (file:///home/stephane/code/aks-rp/swagger/containerservice/fleets.management/node_modules/@typespec/compiler/dist/core/program.js:238:9)
    at async Object.handler (file:///home/stephane/code/aks-rp/swagger/containerservice/fleets.management/node_modules/@typespec/compiler/dist/core/cli/cli.js:114:25)
 ```
    
the tsp files i ran it on to test are the ones from this PR:
    
https://github.com/Azure/azure-rest-api-specs-pr/pull/11615/files#diff-52d57fc73af08f92895030a57d5e6201d952cff7109eafec2ed67dba6e2ec603R42

**Comment by tjprescott** [comment]
@serbrech what dependencies are you using? When I try and follow your repro I get 250 errors just in compilation--before it even gets to APIView.

Where is your package.json?

**Comment by serbrech** [comment]
I'm using the latest typespec

**Comment by tjprescott** [comment]
There are more dependencies than the typespec compiler. Looking at the enums in your spec the only thing that stands out is where you have an enum that just uses the spread operator. I'll take a look and see if that causes an issue.
