### ISSUE TITLE
Creating new TypeSpec SDK for using docker fails

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#5756]
I'm working on our sample data-plane project and converting it to TypeSpec and trying to run the docker container to generate the .NET SDK and hitting the following issue. 

Looks like we still need to update the cadl to typespec and given this sample isn't in the .NET repo I would have expected it to create a new cadl-location file for me automatically. 

```
> docker run -it --privileged -v d:\adp\azure-rest-api-specs:/spec-repo -v d:\adp:/work-dir sdkgeneration.azurecr.io/sdk-generation:beta-1.0 --cadl-project="specification/contosowidgetmanager/Contoso.WidgetManager" --sdk=.net
2023-03-20 04:44:53 info        Preparing environment to generate codes and do grow up development in local
2023-03-20 04:44:53 info        Start to run task engine in azure-sdk-for-net
2023-03-20 04:44:53 info        Get codegen_to_sdk_config.json
2023-03-20 04:44:53 info        {
  "init": {
    "initScript": {
      "path": "./eng/scripts/automation/init.sh",
      "logPrefix": "[DotNet]",
      "stderr": {
        "storeAllLog": true
      },
      "envs": []
    }
  },
  "generateAndBuild": {
    "generateAndBuildScript": {
      "path": "./eng/scripts/automation/Invoke-GenerateAndBuild.ps1",
      "script": "pwsh",
      "logPrefix": "[DotNet-Generate]",
      "stderr": {
        "storeLogByFilter": "[error|Error|Exception]"
      },
      "envs": []
    }
  },
  "mockTest": {
    "mockTestScript": {
      "path": "./eng/scripts/automation/Invoke-MockTest.ps1",
      "script": "pwsh",
      "logPrefix": "[GO-MockTest]",
      "stderr": {
        "storeLogByFilter": "[error|Error|Exception]"
      },
      "envs": []
    }
  }
}
2023-03-20 04:44:53 info        Get tasks to run: InitTask,GenerateAndBuildTask,MockTestTask
2023-03-20 04:44:53 cmdout      task script path:/work-dir/azure-sdk-for-net/eng/scripts/automation/init.sh
2023-03-20 04:44:53 cmdout      chmod
2023-03-20 04:44:53 cmdout      [[DotNet]] /tmp/output/initOutput.json

2023-03-20 04:44:54 cmdout      [[DotNet]] GET https://dot.net/v1/dotnet-install.sh

2023-03-20 04:44:56 cmdout      [[DotNet]] dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.

2023-03-20 04:44:56 cmdout      [[DotNet]] dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.


2023-03-20 04:44:58 cmdout      [[DotNet]] dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.407/dotnet-sdk-6.0.407-linux-x64.tar.gz

2023-03-20 04:45:25 cmdout      [[DotNet]] dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.407/dotnet-sdk-6.0.407-linux-x64.tar.gz

2023-03-20 04:45:56 cmdout      [[DotNet]] dotnet-install: Installed version is 6.0.407

2023-03-20 04:45:56 cmdout      [[DotNet]] dotnet-install: Adding to current process PATH: `/work-dir/azure-sdk-for-net/.dotnet`. Note: This change will be visible only when sourcing script.

2023-03-20 04:45:56 cmdout      [[DotNet]] dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.

2023-03-20 04:45:56 cmdout      [[DotNet]] dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:

2023-03-20 04:45:56 cmdout      [[DotNet]] dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.


2023-03-20 04:45:58 cmdout      [[DotNet]] dotnet-install: Attempting to download using primary link https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.426/dotnet-sdk-3.1.426-linux-x64.tar.gz

2023-03-20 04:46:17 cmdout      [[DotNet]] dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.426/dotnet-sdk-3.1.426-linux-x64.tar.gz

2023-03-20 04:46:33 cmdout      [[DotNet]] dotnet-install: Installed version is 3.1.426

2023-03-20 04:46:33 cmdout      [[DotNet]] dotnet-install: Adding to current process PATH: `/work-dir/azure-sdk-for-net/.dotnet`. Note: This change will be visible only when sourcing script.
dotnet-install: Note that the script does not resolve dependencies during installation.

2023-03-20 04:46:33 cmdout      [[DotNet]] dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.

2023-03-20 04:46:33 cmdout      [[DotNet]] dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.

2023-03-20 04:46:33 cmdout      [[DotNet]] dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.


2023-03-20 04:46:34 cmdout      [[DotNet]] dotnet-install: Attempting to download using primary link https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.101/dotnet-sdk-7.0.101-linux-x64.tar.gz

2023-03-20 04:47:03 cmdout      [[DotNet]] dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.101/dotnet-sdk-7.0.101-linux-x64.tar.gz

2023-03-20 04:47:30 cmdout      [[DotNet]] dotnet-install: Installed version is 7.0.101

2023-03-20 04:47:30 cmdout      [[DotNet]] dotnet-install: Adding to current process PATH: `/work-dir/azure-sdk-for-net/.dotnet`. Note: This change will be visible only when sourcing script.

2023-03-20 04:47:30 cmdout      [[DotNet]] dotnet-install: Note that the script does not resolve dependencies during installation.
dotnet-install: To check the list of dependencies, go to https://learn.microsoft.com/dotnet/core/install, select your operating system and check the "Dependencies" section.
dotnet-install: Installation finished successfully.

2023-03-20 04:47:30 cmdout      [[DotNet]] 3.1.426 [/root/.dotnet/sdk]
6.0.406 [/root/.dotnet/sdk]
7.0.101 [/root/.dotnet/sdk]

2023-03-20 04:47:31 cmdout      [[DotNet]] /work-dir/azure-sdk-for-net

2023-03-20 04:47:31 cmdout      [[DotNet]] /work-dir/azure-sdk-for-net/.dotnet/dotnet

2023-03-20 04:47:31 cmdout      [[DotNet]] 3.1.426 [/work-dir/azure-sdk-for-net/.dotnet/sdk]
6.0.407 [/work-dir/azure-sdk-for-net/.dotnet/sdk]
7.0.101 [/work-dir/azure-sdk-for-net/.dotnet/sdk]

2023-03-20 04:47:31 cmdout      [[DotNet]] /tmp/output/initOutput.json

2023-03-20 04:47:31 cmdout      [[DotNet]] {
  "envs": {
    "PATH": "/work-dir/azure-sdk-for-net/.dotnet:/work-dir/azure-sdk-for-net/.dotnet:/root/.dotnet:/usr/maven/bin:/usr/java/openjdk-17/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "DOTNET_ROOT": "/work-dir/azure-sdk-for-net/.dotnet"
  }
}

2023-03-20 04:47:31 info        Get initOutput.json:
2023-03-20 04:47:31 info        {
  "envs": {
    "PATH": "/work-dir/azure-sdk-for-net/.dotnet:/work-dir/azure-sdk-for-net/.dotnet:/root/.dotnet:/usr/maven/bin:/usr/java/openjdk-17/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
    "DOTNET_ROOT": "/work-dir/azure-sdk-for-net/.dotnet"
  }
}
2023-03-20 04:47:31 info        Get generateAndBuildInput.json:
2023-03-20 04:47:31 info        {
  "specFolder": "/spec-repo/specification",
  "headSha": "",
  "headRef": "ConvertSampleToTypeSpec",
  "repoHttpsUrl": "https://github.com/weshaggard/azure-rest-api-specs",
  "serviceType": "data-plane",
  "skipGeneration": false,
  "relatedCadlProjectFolder": "contosowidgetmanager/Contoso.WidgetManager"
}
2023-03-20 04:47:31 cmdout      task script path:/work-dir/azure-sdk-for-net/eng/scripts/automation/Invoke-GenerateAndBuild.ps1
2023-03-20 04:47:31 cmdout      chmod
2023-03-20 04:47:32 cmderr      [[DotNet-Generate]] Get-Content: /work-dir/azure-sdk-for-net/eng/scripts/automation/Invoke-GenerateAndBuild.ps1:76
Line |
  76 |  … ojectYaml = Get-Content -Path (Join-Path "$cadlFolder" "cadl-project. …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path
     | '/spec-repo/specification/contosowidgetmanager/Contoso.WidgetManager/cadl-project.yaml' because it does not exist.

2023-03-20 04:47:39 cmdout      [[DotNet-Generate]] Installing module powershell-yaml with min version 0.4.1 from https://www.powershellgallery.com/api/v2

2023-03-20 04:47:41 cmdout      [[DotNet-Generate]] Using module powershell-yaml with version 0.4.7.

2023-03-20 04:47:42 cmderr      [[DotNet-Generate]] Exception: /work-dir/azure-sdk-for-net/eng/scripts/automation/Invoke-GenerateAndBuild.ps1:91
Line |
  91 |        throw "Not provide service name or namespace."
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Not provide service name or namespace.

2023-03-20 04:47:42 cmderr      Script return with result [failed] code [1] signal [null] cwd [/work-dir/azure-sdk-for-net]: ./eng/scripts/automation/Invoke-GenerateAndBuild.ps1
2023-03-20 04:52:42 info        Finish running task engine in azure-sdk-for-net
 Error: Execute generateAndBuild script failed.
 Execute generateAndBuild script failed.
 Error: Execute generateAndBuild script failed.
    at GenerateAndBuildTask.execute (/usr/lib/node_modules/@azure-tools/sdk-generation-cli/dist/cli/dockerCli/core/tasks/GenerateAndBuildTask.js:59:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async DockerTaskEngineContext.runTaskEngine (/usr/lib/node_modules/@azure-tools/sdk-generation-cli/dist/cli/dockerCli/core/DockerTaskEngineContext.js:137:17)
    at async GenerateCodesInLocalJob.execute (/usr/lib/node_modules/@azure-tools/sdk-generation-cli/dist/cli/dockerCli/core/jobs/GenerateCodesInLocalJob.js:54:13)
    at async main (/usr/lib/node_modules/@azure-tools/sdk-generation-cli/dist/cli/dockerCli/dockerCli.js:27:9)
```

**Comment by weshaggard** [comment]
For reference the spec PR with the TypeSpec update is https://github.com/Azure/azure-rest-api-specs/pull/23168.

**Comment by chunyu3** [comment]
We are updating the .net script to rename typespec.  this is the PR https://github.com/Azure/azure-sdk-for-net/pull/34058.

**Comment by raych1** [comment]
This docker code base has been deprecated.
