### ISSUE TITLE
Swagger API review gen failure to get operations

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5810]
Found following swagger API parser run failure for Microsoft.Synapse.

```
The generated code file is /mnt/vss/_work/1/generated/Microsoft.Synapse/Microsoft.Synapse.New.json
Changing directory and executing the function...
swaggerAPIParser input file specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/azureADOnlyAuthentication.json,specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/checkNameAvailability.json,specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/firewallRule.json,specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/keys.json,specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/operations.json,specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/privateEndpointConnections.json,specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/privateLinkResources.json,specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/privatelinkhub.json,specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/sqlPool.json,specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/sqlServer.json,specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/workspace.json,specification/synapse/resource-manager/Microsoft.Synapse/preview/2021-06-01-preview/bigDataPool.json,specification/synapse/resource-manager/Microsoft.Synapse/preview/2021-06-01-preview/library.json,specification/synapse/resource-manager/Microsoft.Synapse/preview/2021-06-01-preview/integrationRuntime.json,specification/synapse/resource-manager/Microsoft.Synapse/preview/2021-06-01-preview/sparkConfiguration.json,specification/synapse/resource-manager/Microsoft.Synapse/preview/2021-06-01-preview/kustoPool.json, branch: main
Get resource provider resourceProvider: Microsoft.Synapse, from path specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/azureADOnlyAuthentication.json
commonTypesFiles: /mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/data-plane/v1/types.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v1/privatelinks.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v1/types.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v2/privatelinks.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v2/types.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v3/managedidentity.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v3/privatelinks.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v3/types.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v4/customermanagedkeys.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v4/managedidentity.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v4/managedidentitywithdelegation.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v4/privatelinks.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v4/types.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v5/managedidentity.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v5/types.json,/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/rfcs/rfc7517.json
exec command: echo $HOME&&$HOME/.dotnet/tools/swaggerAPIParser --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/azureADOnlyAuthentication.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/checkNameAvailability.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/firewallRule.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/keys.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/operations.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/privateEndpointConnections.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/privateLinkResources.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/privatelinkhub.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/sqlPool.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/sqlServer.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/stable/2021-06-01/workspace.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/preview/2021-06-01-preview/bigDataPool.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/preview/2021-06-01-preview/library.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/preview/2021-06-01-preview/integrationRuntime.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/preview/2021-06-01-preview/sparkConfiguration.json" --swaggers "specification/synapse/resource-manager/Microsoft.Synapse/preview/2021-06-01-preview/kustoPool.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/data-plane/v1/types.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v1/privatelinks.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v1/types.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v2/privatelinks.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v2/types.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v3/managedidentity.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v3/privatelinks.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v3/types.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v4/customermanagedkeys.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v4/managedidentity.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v4/managedidentitywithdelegation.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v4/privatelinks.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v4/types.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v5/managedidentity.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/resource-management/v5/types.json" --swaggers "/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/specification/common-types/rfcs/rfc7517.json" --output /mnt/vss/_work/1/generated/Microsoft.Synapse/Microsoft.Synapse.Baseline.json --package-name Microsoft.Synapse
Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at SwaggerApiParser.ApiPath.get_operations() in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerSpec/ApiPath.cs:line 35
   at SwaggerApiParser.SwaggerApiViewGenerator.GenerateSwaggerApiView(SwaggerSpec swaggerSpec, String swaggerFilePath, SchemaCache schemaCache, String packageName, String swaggerLink) in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerAPIViewGenerator.cs:line 48
   at SwaggerApiParser.Program.HandleGenerateCodeFile(IEnumerable`1 swaggers, String output, String packageName, List`1 swaggerLinks, String readmeFile, String readmeTag) in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/Program.cs:line 109
   at SwaggerApiParser.Program.<>c.<<Main>b__0_3>d.MoveNext() in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/Program.cs:line 57
--- End of stack trace from previous location ---
```

**Comment by chidozieononiwu** [comment]
Resolved by https://github.com/Azure/azure-sdk-tools/pull/5914
