### ISSUE TITLE
NullReferenceExcetion when generating operation table for PR

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#5837]
Checks on PR Azure/azure-rest-api-specs#23290 failed with:

```
Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at SwaggerApiParser.BaseSchema.GetTypeFormat() in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerSpec/SwaggerTypes.cs:line 134
   at SwaggerApiParser.SwaggerApiViewParameter.GetTypeFormat() in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewParameter.cs:line 40
   at SwaggerApiParser.SwaggerApiViewOperationParameters.TokenSerializeTableRows(SerializeContext context) in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewParameter.cs:line 148
   at SwaggerApiParser.SwaggerApiViewOperationParameters.TokenSerialize(SerializeContext context) in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewParameter.cs:line 136
   at SwaggerApiParser.SwaggerApiViewOperation.TokenSerialize(SerializeContext context) in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewOperation.cs:line 104
   at SwaggerApiParser.SwaggerApiViewPaths.TokenSerialize(SerializeContext context) in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewPaths.cs:line 101
   at SwaggerApiParser.SwaggerApiViewSpec.TokenSerialize(SerializeContext context) in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewSpec.cs:line 47
   at SwaggerApiParser.SwaggerApiViewRoot.TokenSerialize(SerializeContext context) in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewRoot.cs:line 66
   at SwaggerApiParser.SwaggerApiViewRoot.GenerateCodeFile() in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/SwaggerApiView/SwaggerApiViewRoot.cs:line 40
   at SwaggerApiParser.Program.HandleGenerateCodeFile(IEnumerable`1 swaggers, String output, String packageName, List`1 swaggerLinks, String readmeFile, String readmeTag) in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/Program.cs:line 109
   at SwaggerApiParser.Program.<>c.<<Main>b__0_3>d.MoveNext() in /mnt/vss/_work/1/s/tools/apiview/parsers/swagger-api-parser/SwaggerApiParser/Program.cs:line 57

**Comment by mikekistler** [comment]
Making this high priority at least to get debug done and understand the scenario. May lower later.

**Comment by chidozieononiwu** [comment]
Resolved by https://github.com/Azure/azure-sdk-tools/pull/6009
