### ISSUE TITLE
Open API portal is showing failure when creating a new API version for KeyVault

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#6051]
Open API portal is showing failure when creating a new API version for KeyVault with following error message `Branch contains changes to more or less than one resource provider. Currently only changes to one resource provider are supported`

Link to Open API request: [release-keyvault-Microsoft.KeyVault-7.5-preview.1](https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/release-keyvault-Microsoft.KeyVault-7.5-preview.1)

GitHub branch was successfully created but it failed to get work item.

Error details: 
```URL: https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/release-keyvault-Microsoft.KeyVault-7.5-preview.1

ApiError: Branch contains changes to more or less than one resource provider. Currently only changes to one resource provider are supported.
    During API GET_WORK_ITEM({"owner":"Azure","repo":"azure-rest-api-specs","branch":"release-keyvault-Microsoft.KeyVault-7.5-preview.1","baseBranch":"main"})
    at https://portal.azure-devex-tools.com/static/build.js:415:147161
    at Generator.next (<anonymous>)
    at a (https://portal.azure-devex-tools.com/static/build.js:415:146160)
The above error occurred in task GET_WORK_ITEM
    created by WORK_ITEM_PAGE/MOUNT
    created by anonymous
```

**Comment by praveenkuttappan** [comment]
Another instance of same failure:
```
URL: https://portal.azure-devex-tools.com/branch/Azure/azure-rest-api-specs/adarce-keyvault-Microsoft.KeyVault-7.6-preview.1...main/ApiError: Branch contains changes to more or less than one resource provider. Currently only changes to one resource provider are supported.    During API GET_WORK_ITEM({"owner":"Azure","repo":"azure-rest-api-specs","branch":"adarce-keyvault-Microsoft.KeyVault-7.6-preview.1","baseBranch":"main"})    at https://portal.azure-devex-tools.com/static/build.js:415:147161    at Generator.next (<anonymous>)    at a (https://portal.azure-devex-tools.com/static/build.js:415:146160)The above error occurred in task GET_WORK_ITEM    created by WORK_ITEM_PAGE/MOUNT    created by anonymous
```
