### ISSUE TITLE
[Test-Proxy] .NET Security Update Breaks Certificate Creation

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#6357]
[see this build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2851317&view=logs&j=2d72bf5f-9a0c-5aa3-6e85-aec77a4486f7&t=71826648-8fa0-5027-ec86-1fe5798108f0&l=48)

```
[xUnit.net 00:00:02.17]     Azure.Sdk.Tools.TestProxy.Tests.RecordingHandlerTests.TestSetRecordingOptionsValidTransportSessionLevel(body: "{{\"Transport\": {{\"Certificates\": [ {{ \"PemVal"...) [FAIL]
  Failed Azure.Sdk.Tools.TestProxy.Tests.RecordingHandlerTests.TestSetRecordingOptionsValidTransportSessionLevel(body: "{{\"Transport\": {{\"Certificates\": [ {{ \"PemVal"...) [87 ms]
  Error Message:
   Azure.Sdk.Tools.TestProxy.Common.Exceptions.HttpException : Unable to instantiate a new X509 certificate from the provided value and key. Failure Message: "PKCS12 (PFX) without a supplied password has exceeded maximum allowed iterations. See https://go.microsoft.com/fwlink/?linkid=2233907 for more information.".
  Stack Trace:
     at Azure.Sdk.Tools.TestProxy.RecordingHandler.GetTransport(Boolean allowAutoRedirect, TransportCustomizations customizations, Boolean insecure) in D:\a\_work\1\s\tools\test-proxy\Azure.Sdk.Tools.TestProxy\RecordingHandler.cs:line 717
   at Azure.Sdk.Tools.TestProxy.RecordingHandler.SetTransportOptions(TransportCustomizations customizations, String sessionId) in D:\a\_work\1\s\tools\test-proxy\Azure.Sdk.Tools.TestProxy\RecordingHandler.cs:line 797
   at Azure.Sdk.Tools.TestProxy.RecordingHandler.SetRecordingOptions(IDictionary`2 options, String sessionId) in D:\a\_work\1\s\tools\test-proxy\Azure.Sdk.Tools.TestProxy\RecordingHandler.cs:line 661
   at Azure.Sdk.Tools.TestProxy.Tests.RecordingHandlerTests.TestSetRecordingOptionsValidTransportSessionLevel(String body) in D:\a\_work\1\s\tools\test-proxy\Azure.Sdk.Tools.TestProxy.Tests\RecordingHandlerTests.cs:line 988
```

This is a new error that just started popping up. This is due to the fact that security update which enforces this rolled out on June 12th 2023. I believe it just now hit our agents.

Need to update the callsite, add an environment variable, or _something_, but [this discussion link](https://support.microsoft.com/en-us/topic/kb5025823-change-in-how-net-applications-import-x-509-certificates-bf81c936-af2b-446e-9f7a-016f4713b46b#:~:text=To%20change%20the%20limit%2C%20under%20the%20registry%20key,as%20shown%20below%20from%20an%20elevated%20command%20prompt.) has some good methods to remediate.

**Comment by scbedd** [comment]
Resolved by #6358
