### ISSUE TITLE
CadlApiView Error While the CadlValidation Success

### ISSUE THREAD

**Issue by JackTn** [Azure/azure-sdk-tools#6377]
Here is another PR https://github.com/Azure/azure-rest-api-specs-pr/pull/12858 which CADL Validation is success but CadlAPIView Error with https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2861797&view=logs&j=9e7477d6-80c4-54a8-ebef-1e18da128ba0&t=f4a3c60c-600e-599b-d672-ffecbc71e09d&l=112
`Error: ENOENT: no such file or directory, open '/mnt/vss/_work/1/generated/unknown/_meta.json'
    at Object.openSync (fs.js:498:3)
    at Object.writeFileSync (fs.js:1529:35)
    at runSwaggerAPIViewOnTag (/mnt/vss/_work/1/a/unified-pipeline-runtime/public/rest-api-specs-scripts/dist/swaggerAPIView.js:155:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.runSwaggerAPIView (/mnt/vss/_work/1/a/unified-pipeline-runtime/public/rest-api-specs-scripts/dist/swaggerAPIView.js:167:13) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/mnt/vss/_work/1/generated/unknown/_meta.json'
}`

**Comment by JackTn** [comment]
@maririos

**Comment by mikekistler** [comment]
CadlApiView is replaced with TypeSpec APIView.
