### ISSUE TITLE
[PR Workflow][PR Summary] fails on README removal

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#6672]
## Workaround

If you are an author of a specs PR affected by this this issue, then revert `README` file removal from the PR.

## Description

- https://github.com/Azure/azure-rest-api-specs-pr/pull/14099
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2973560&view=logs&j=d6a48a56-e996-55ca-2302-c3a9a7be685b&t=f4162ac4-a5be-580e-39db-db0d6209bd6a&l=112
- [Teams discussion](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1691078145687?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1691078145687&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1691078145687)

```
error checking PR summary
Error: ENOENT: no such file or directory, open 'specification/edgesites/resource-manager/readme.md'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at new ReadmeParser (/mnt/vss/_work/1/a/unified-pipeline-runtime/public/rest-api-specs-scripts/dist/readmeUtils.js:38:35)
    at isRPSaaS (/mnt/vss/_work/1/a/unified-pipeline-runtime/public/rest-api-specs-scripts/dist/prSummary.js:305:26)
    at Object.ReadmeFile (/mnt/vss/_work/1/a/unified-pipeline-runtime/public/rest-api-specs-scripts/dist/prSummary.js:292:48)
    at /mnt/vss/_work/1/a/unified-pipeline-runtime/public/rest-api-specs-scripts/dist/prSummaryUtils.js:11:116
    at Array.forEach (<anonymous>)
    at /mnt/vss/_work/1/a/unified-pipeline-runtime/public/rest-api-specs-scripts/dist/prSummaryUtils.js:8:18
    at Array.forEach (<anonymous>)
    at Object.processPrChanges (/mnt/vss/_work/1/a/unified-pipeline-runtime/public/rest-api-specs-scripts/dist/prSummaryUtils.js:7:12) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'specification/edgesites/resource-manager/readme.md'
}
```

Rerunning with `/azp run` doesn't help.

**Comment by konrad-jamrozik** [comment]
Another case:

[Teams discussion](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1691454510467?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1691447488501&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1691454510467)

**Comment by konrad-jamrozik** [comment]
Another case:
- https://github.com/Azure/azure-rest-api-specs-pr/pull/16646

**Comment by konrad-jamrozik** [comment]
Another case:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3426669&view=logs&j=d6a48a56-e996-55ca-2302-c3a9a7be685b&t=f4162ac4-a5be-580e-39db-db0d6209bd6a&l=157

Bumping priority of this item.

@weshaggard FYI

**Comment by konrad-jamrozik** [comment]
- [Pull Request 524427](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/524427): Fix incorrect file diffs for README, thus bugfixing issues with readme removal
