### ISSUE TITLE
[LiveValidate RPaaS] Newest image version crashes validation of `networkFunctions` service request

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#6781]
image version: `v1.5.0.20230806.1` 

```text
API (response) validation failed for resource 'Microsoft.HybridNetwork/networkFunctions/RunnerCNF' with runtime exception : code 'REQUEST_VALIDATION_ERROR'; message 'An error occurred while validating the live response for operation \"NetworkFunctions_CreateOrUpdate\". The error is:\n TypeError: Cannot read properties of null (reading 'id')\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:1470)\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:2849)\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:1595)\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:770)\n
    at validateSchema (/usr/app/node_modules/oav/dist/lib/swaggerValidator/ajvSchemaValidator.js:91:53)\n
    at exports.validateSwaggerLiveResponse (/usr/app/node_modules/oav/dist/lib/liveValidation/operationValidator.js:86:20)\n
    at LiveValidator.validateLiveResponse (/usr/app/node_modules/oav/dist/lib/liveValidation/liveValidator.js:318:49)\n
    at Validator.validateResponse (/usr/app/dist/src/lib/validator.js:215:49)\n
    at ValidationController.validateResponse (/usr/app/dist/src/controllers/validationController.js:55:28)\n
    at InversifyExpressServer.<anonymous> (/usr/app/node_modules/inversify-express-utils/lib/server.js:202:124)'. Complete validaton result : {\"operationInfo\":{\"operationId\":\"NetworkFunctions_CreateOrUpdate\",\"apiVersion\":\"2021-05-01\"},\"errors\":[],\"runtimeException\":{\"code\":\"REQUEST_VALIDATION_ERROR\",\"message\":\"An error occurred while validating the live response for operation \\\"NetworkFunctions_CreateOrUpdate\\\". The error is:\\n TypeError: Cannot read properties of null (reading 'id')\\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:1470)\\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:2849)\\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:1595)\\n
    at Object.validate (eval at localCompile (/usr/app/node_modules/ajv/lib/compile/index.js:120:26), <anonymous>:3:770)\\n
    at validateSchema (/usr/app/node_modules/oav/dist/lib/swaggerValidator/ajvSchemaValidator.js:91:53)\\n
    at exports.validateSwaggerLiveResponse (/usr/app/node_modules/oav/dist/lib/liveValidation/operationValidator.js:86:20)\\n
    at LiveValidator.validateLiveResponse (/usr/app/node_modules/oav/dist/lib/liveValidation/liveValidator.js:318:49)\\n
    at Validator.validateResponse (/usr/app/dist/src/lib/validator.js:215:49)\\n
    at ValidationController.validateResponse (/usr/app/dist/src/controllers/validationController.js:55:28)\\n
    at InversifyExpressServer.<anonymous> (/usr/app/node_modules/inversify-express-utils/lib/server.js:202:124)\"}}
```

This caused a reversion of production rollout. Need to get payload details from RPaaS folks so that we can repro and issue a fix.

**Comment by scbedd** [comment]
```json
{
    "id": "/subscriptions/6c204db9-7efd-4adb-98ac-e982a6e28084/resourceGroups/rgname/providers/Microsoft.HybridNetwork/networkFunctions/nf0001",
    "name": "nf0001",
    "type": "microsoft.hybridnetwork/networkfunctions",
    "location": "eastus2euap",
    "systemData": {
        "createdBy": "alias@microsoft.com",
        "createdByType": "User",
        "createdAt": "2023-08-16T00:47:52.8414851Z",
        "lastModifiedBy": "alias@microsoft.com",
        "lastModifiedByType": "User",
        "lastModifiedAt": "2023-08-16T00:47:52.8414851Z"
    },
    "properties": {
        "provisioningState": "Accepted",
        "device": null,
        "skuName": "cnfsku1",
        "skuType": "EvolvedPacketCore",
        "vendorName": "v1",
        "serviceKey": "6c204db9-7efd-4adb-98ac-e982a6e28084",
        "vendorProvisioningState": "NotProvisioned",
        "managedApplication": null,
        "managedApplicationParameters": {
            "extendedLocation": {
                "Name": "/subscriptions/6c204db9-7efd-4adb-98ac-e982a6e28084/resourceGroups/rgname2/providers/Microsoft.ExtendedLocation/customLocations/nagouCl011",
                "Type": "CustomLocation"
            },
            "vendorConfigurations": {
                "releaseName": "cnf-runner-test",
                "targetNamespace": "cnf-runner-test",
                "values": "{\"repoBase\":\"xyz.azurecr.io3/\"}"
            },
            "userConfigurations": {}
        },
        "networkFunctionUserConfigurations": null
    }
}
```

**Comment by scbedd** [comment]
[Created branch](https://devdiv.visualstudio.com/DevDiv/_git/openapi-platform?version=GBfeature%2Fsupport-networkfunctions-call)

Debugging through to `oav`.

**Comment by scbedd** [comment]
This is caused by _some_ change in oav. `validate-v2` image versions before `oav` update `3.2.8` are solid. It's after that are the problem. Given that this is strictly a crash in oav, going to xfer this issue there.
