### ISSUE TITLE
invalid breaking change: incompatible properties : tags 

### ISSUE THREAD

**Issue by cataggar** [Azure/azure-sdk-tools#7917]
I'm also getting breaking changes for `tags`: `"details":"incompatible properties : tags "`.
https://github.com/Azure/azure-rest-api-specs-pr/pull/17544/checks?check_run_id=22852786355

There were no changes for it in the PR. It is reported as broken in all of the PRs.

**Comment by cataggar** [comment]
Added [internal Teams thread](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1710947114434?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1710947114434&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1710947114434).

**Comment by mikeharder** [comment]
This looks like a bug in https://github.com/Azure/openapi-diff.  It fails comparing a spec to itself.

```
$ npx @azure/oad compare
   specification/vmware/resource-manager/Microsoft.AVS/preview/2024-09-01-preview/vmware.json 
   specification/vmware/resource-manager/Microsoft.AVS/preview/2024-09-01-preview/vmware.json

  Error: incompatible properties : tags
    at /home/mharder/.npm/_npx/e8607a6f0f0d8b1b/node_modules/@azure/oad/dist/lib/util/resolveSwagger.js:240:35
    at /home/mharder/.npm/_npx/e8607a6f0f0d8b1b/node_modules/@ts-common/iterator/dist/index.js:158:40
    at exports.fold (/home/mharder/.npm/_npx/e8607a6f0f0d8b1b/node_modules/@ts-common/iterator/dist/index.js:138:18)
    at exports.forEach (/home/mharder/.npm/_npx/e8607a6f0f0d8b1b/node_modules/@ts-common/iterator/dist/index.js:158:13)
    at Object.forEach (/home/mharder/.npm/_npx/e8607a6f0f0d8b1b/node_modules/@ts-common/iterator/dist/index.js:5:39)
    at ResolveSwagger.ExpandAllOf (/home/mharder/.npm/_npx/e8607a6f0f0d8b1b/node_modules/@azure/oad/dist/lib/util/resolveSwagger.js:237:49)
    at ResolveSwagger.ExpandDefinitions (/home/mharder/.npm/_npx/e8607a6f0f0d8b1b/node_modules/@azure/oad/dist/lib/util/resolveSwagger.js:210:22)
    at ResolveSwagger.resolve (/home/mharder/.npm/_npx/e8607a6f0f0d8b1b/node_modules/@azure/oad/dist/lib/util/resolveSwagger.js:101:14)
    at OpenApiDiff.processViaAutoRest (/home/mharder/.npm/_npx/e8607a6f0f0d8b1b/node_modules/@azure/oad/dist/lib/validators/openApiDiff.js:198:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

But it succeeds comparing the previous version to itself

```
$ npx @azure/oad compare
  specification/vmware/resource-manager/Microsoft.AVS/preview/2021-01-01-preview/vmware.json
  specification/vmware/resource-manager/Microsoft.AVS/preview/2021-01-01-preview/vmware.json

[{​​​​​​​"id":"1001","code":"NoVersionChange","message":"The versions have not changed.","old":{​​​​​​​"ref":"file:///home/mharder/specs-pr/specification/vmware/resource-manager/Microsoft.AVS/preview/2021-01-01-preview/vmware.json#","path":"","location":"file:///home/mharder/specs-pr/specification/vmware/resource-manager/Microsoft.AVS/preview/2021-01-01-preview/vmware.json:1:1"}​​​​​​​,"new":{​​​​​​​"ref":"file:///home/mharder/specs-pr/specification/vmware/resource-manager/Microsoft.AVS/preview/2021-01-01-preview/vmware.json#","path":"","location":"file:///home/mharder/specs-pr/specification/vmware/resource-manager/Microsoft.AVS/preview/2021-01-01-preview/vmware.json:1:1"}​​​​​​​,"type":"Info","docUrl":"[https://github.com/Azure/openapi-diff/tree/master/docs/rules/1001.md","mode":"Update"}​​​​​​​​]](https://github.com/Azure/openapi-diff/tree/master/docs/rules/1001.md%22,%22mode%22:%22Update%22%7D%E2%80%8B])
```

`autorest` itself succeeds:

```
$ npx autorest --v2
  --input-file=specification/vmware/resource-manager/Microsoft.AVS/preview/2024-09-01-preview/vmware.json
  
AutoRest code generation utility [cli version: 3.7.1; node: v20.11.1]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ~2.0.4413.
   Loading AutoRest core      '/home/mharder/.autorest/@microsoft.azureautorest-core@2.0.4427/nodemodules/@microsoft.azure/autorest-core/dist' (2.0.4427)
```

**Comment by mikeharder** [comment]
Issue was in spec.  This TypeSpec:

``` 
model PrivateCloud is TrackedResource<PrivateCloudProperties> {
  ...ArmTagsProperty;
```

Generated swagger with slightly different `tags` properties.  The fix was to remove `ArmTagsProperty` from the spec.
