### ISSUE TITLE
Emitter "@azure-tools/typespec-apiview" crashed, Error: Case "35" not implemented

### ISSUE THREAD

**Issue by Han-msft** [Azure/azure-sdk-tools#7930]
Our pipeline build for TypeSpec  APIView broke recently.

Here is the error message
```
Compiling files and generating APIView
Executing command: npx tsp compile . --emit=@azure-tools/typespec-apiview --option @azure-tools/typespec-apiview.emitter-output-dir={project-root}/output/apiview.json in folder: specification/ai/Face
stderr: Emitter "@azure-tools/typespec-apiview" crashed! This is a bug.
Please file an issue at https://github.com/Azure/azure-sdk-tools/issues

Error: Case "35" not implemented
    at ApiView.tokenize (file:///mnt/vss/_work/1/azure-rest-api-specs/specification/node_modules/@azure-tools/typespec-apiview/dist/src/apiview.js:528:23)
    at ApiView.tokenize (file:///mnt/vss/_work/1/azure-rest-api-specs/specification/node_modules/@azure-tools/typespec-apiview/dist/src/apiview.js:327:30)
    at ApiView.tokenizeDecorators (file:///mnt/vss/_work/1/azure-rest-api-specs/specification/node_modules/@azure-tools/typespec-apiview/dist/src/apiview.js:807:18)
    at ApiView.tokenizeOperationStatement (file:///mnt/vss/_work/1/azure-rest-api-specs/specification/node_modules/@azure-tools/typespec-apiview/dist/src/apiview.js:736:14)
    at ApiView.tokenize (file:///mnt/vss/_work/1/azure-rest-api-specs/specification/node_modules/@azure-tools/typespec-apiview/dist/src/apiview.js:415:22)
    at ApiView.tokenizeNamespaceModel (file:///mnt/vss/_work/1/azure-rest-api-specs/specification/node_modules/@azure-tools/typespec-apiview/dist/src/apiview.js:759:18)
    at ApiView.emit (file:///mnt/vss/_work/1/azure-rest-api-specs/specification/node_modules/@azure-tools/typespec-apiview/dist/src/apiview.js:250:22)
    at Object.emitApiView (file:///mnt/vss/_work/1/azure-rest-api-specs/specification/node_modules/@azure-tools/typespec-apiview/dist/src/emitter.js:159:21)
    at Object.$onEmit [as emitFunction] (file:///mnt/vss/_work/1/azure-rest-api-specs/specification/node_modules/@azure-tools/typespec-apiview/dist/src/emitter.js:9:19)
    at runEmitter (file:///mnt/vss/_work/1/azure-rest-api-specs/specification/node_modules/@typespec/compiler/dist/src/core/program.js:554:27)
```

Link to TypeSpec PR: https://github.com/Azure/azure-rest-api-specs/pull/27576
Link to Pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3623359&view=logs&j=e37a1bb9-a190-5269-3a0e-37469dfbe682&t=09cb0672-20c5-5dce-4552-dad3f3e96fd3

**Comment by tjprescott** [comment]
Case 35 is "StringTemplateExpression", added by https://github.com/microsoft/typespec/pull/2630

I'll work on a fix but if you are blocked you could eliminate the string templates in your spec.
