### ISSUE TITLE
[SDK Automation - Go] Log the release tags array null reference error gracefully

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8250]
When the array of the release tags fetched from github Go repo is empty, it will throw a null reference exception which ends the current process in the pipeline run. This will stop other SDK generation if the spec PR includes multiple services' spec changes.

This is an [example spec PR](https://github.com/Azure/azure-rest-api-specs/pull/29051) which has this issue. The error is like the following:
```powershell
2024-05-10T19:10:55.6331485Z 07:10:55.632 [4m[33mcmderr[39m[24m 	[generator automation-v2] Fetching all release tags from GitHub for RP: 'mobilepacketcore' Package: 'armmobilepacketcore' ...
2024-05-10T19:10:55.6720029Z 07:10:55.671 [4m[33mcmderr[39m[24m 	[generator automation-v2] panic: runtime error: index out of range [0] with length 0
2024-05-10T19:10:55.6721290Z 07:10:55.671 [4m[33mcmderr[39m[24m 	[generator automation-v2] goroutine 1 [running]:
2024-05-10T19:10:55.6722681Z 07:10:55.672 [4m[33mcmderr[39m[24m 	[generator automation-v2] github.com/Azure/azure-sdk-for-go/eng/tools/generator/cmd/v2/common.GetPreviousVersionTag(0x36?, {0x0?, 0xc0004b4b47?, 0x13?})
2024-05-10T19:10:55.6725033Z 07:10:55.672 [4m[33mcmderr[39m[24m 	[generator automation-v2] 	/mnt/vss/_work/1/s/azure-sdk-for-go/src/github.com/Azure/azure-sdk-for-go/eng/tools/generator/cmd/v2/common/changelogProcessor.go:112 +0x49
2024-05-10T19:10:55.6726389Z 07:10:55.672 [4m[33mcmderr[39m[24m 	[generator automation-v2] github.com/Azure/azure-sdk-for-go/eng/tools/generator/cmd/v2/common.(*GenerateContext).GenerateForSingleRPNamespace(0xc000047630, 0xc000047310)
2024-05-10T19:10:55.6728444Z 07:10:55.672 [4m[33mcmderr[39m[24m 	[generator automation-v2] 	/mnt/vss/_work/1/s/azure-sdk-for-go/src/github.com/Azure/azure-sdk-for-go/eng/tools/generator/cmd/v2/common/generation.go:218 +0xd45
2024-05-10T19:10:55.6729819Z 07:10:55.672 [4m[33mcmderr[39m[24m 	[generator automation-v2] github.com/Azure/azure-sdk-for-go/eng/tools/generator/cmd/v2/common.(*GenerateContext).GenerateForAutomation(0xc000047630, {0xc00194cd50, 0x2d}, {0xcfad78?, 0x1?}, {0xbfc673, 0x4})
2024-05-10T19:10:55.6731074Z 07:10:55.672 [4m[33mcmderr[39m[24m 	[generator automation-v2] 	/mnt/vss/_work/1/s/azure-sdk-for-go/src/github.com/Azure/azure-sdk-for-go/eng/tools/generator/cmd/v2/common/generation.go:83 +0x799
2024-05-10T19:10:55.6732299Z 07:10:55.672 [4m[33mcmderr[39m[24m 	[generator automation-v2] github.com/Azure/azure-sdk-for-go/eng/tools/generator/cmd/v2/automation.(*automationContext).generate(0xc000047b38, 0xc0001fd500)
2024-05-10T19:10:55.6733838Z 07:10:55.672 [4m[33mcmderr[39m[24m 	[generator automation-v2] 	/mnt/vss/_work/1/s/azure-sdk-for-go/src/github.com/Azure/azure-sdk-for-go/eng/tools/generator/cmd/v2/automation/automationCmd.go:128 +0x588
2024-05-10T19:10:55.6735055Z 07:10:55.672 [4m[33mcmderr[39m[24m 	[generator automation-v2] github.com/Azure/azure-sdk-for-go/eng/tools/generator/cmd/v2/automation.execute({0x7ffdcfb2fb8d, 0x36}, {0x7ffdcfb2fbc4, 0x37}, {0xbfc673, 0x4})
2024-05-10T19:10:55.6736276Z 07:10:55.672 [4m[33mcmderr[39m[24m 	[generator automation-v2] 	/mnt/vss/_work/1/s/azure-sdk-for-go/src/github.com/Azure/azure-sdk-for-go/eng/tools/generator/cmd/v2/automation/automationCmd.go:69 +0x453
2024-05-10T19:10:55.6737509Z 07:10:55.672 [4m[33mcmderr[39m[24m 	[generator automation-v2] github.com/Azure/azure-sdk-for-go/eng/tools/generator/cmd.Command.Command.func4(0xc0001fd300?, {0xc0002602e0?, 0x2?, 0xbfc74f?})
2024-05-10T19:10:55.6738520Z 07:10:55.673 [4m[33mcmderr[39m[24m 	[generator automation-v2] 	/mnt/vss/_work/1/s/azure-sdk-for-go/src/github.com/Azure/azure-sdk-for-go/eng/tools/generator/cmd/v2/automation/automationCmd.go:38 +0x5b
2024-05-10T19:10:55.6739324Z 07:10:55.673 [4m[33mcmderr[39m[24m 	[generator automation-v2] github.com/spf13/cobra.(*Command).execute(0xc000237b08, {0xc000260280, 0x2, 0x2})
2024-05-10T19:10:55.6740069Z 07:10:55.673 [4m[33mcmderr[39m[24m 	[generator automation-v2] 	/mnt/vss/_work/1/s/azure-sdk-for-go/src/github.com/Azure/gofolder/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
2024-05-10T19:10:55.6740776Z 07:10:55.673 [4m[33mcmderr[39m[24m 	[generator automation-v2] github.com/spf13/cobra.(*Command).ExecuteC(0xc000236908)
2024-05-10T19:10:55.6741653Z 07:10:55.673 [4m[33mcmderr[39m[24m 	[generator automation-v2] 	/mnt/vss/_work/1/s/azure-sdk-for-go/src/github.com/Azure/gofolder/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
2024-05-10T19:10:55.6742316Z 07:10:55.673 [4m[33mcmderr[39m[24m 	[generator automation-v2] github.com/spf13/cobra.(*Command).Execute(0xc0000061c0?)
2024-05-10T19:10:55.6742988Z 07:10:55.673 [4m[33mcmderr[39m[24m 	[generator automation-v2] 	/mnt/vss/_work/1/s/azure-sdk-for-go/src/github.com/Azure/gofolder/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
2024-05-10T19:10:55.6743621Z 07:10:55.673 [4m[33mcmderr[39m[24m 	[generator automation-v2] main.main()
2024-05-10T19:10:55.6744445Z 07:10:55.673 [4m[33mcmderr[39m[24m 	[generator automation-v2] 	/mnt/vss/_work/1/s/azure-sdk-for-go/src/github.com/Azure/azure-sdk-for-go/eng/tools/generator/main.go:13 +0x18
2024-05-10T19:10:55.6745517Z 07:10:55.674 [31merror[39m C 	Script return with result [failed] code [2] signal [null] cwd [azure-sdk-for-go/src/github.com/Azure/azure-sdk-for-go]: generator automation-v2
2024-05-10T19:10:55.6746500Z 07:10:55.674 [1m[35mendsection[39m[22m 	Call generateScript
2024-05-10T19:10:55.6747702Z 07:10:55.674 [33mwarn[39m 	Skip package processing as generation is failed
```

**Comment by lirenhe** [comment]
Close it as completed
