### ISSUE TITLE
Pipeline notification creator is failing

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#8725]
Example failure: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4005341&view=logs&j=f2ee0415-d5cb-5e2e-67d5-dd79ca5661b0&t=46a932f5-b02b-5d65-82b3-d219e9d05996&l=116
```
      GetDescriptorForAlias UserPrincipal = heaths@microsoft.com
Unhandled exception: Microsoft.VisualStudio.Services.WebApi.VssServiceResponseException: Value cannot be null.
Parameter name: input
 ---> System.ArgumentNullException: Value cannot be null.
Parameter name: input
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponseAsync(HttpResponseMessage response, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync(HttpRequestMessage message, HttpCompletionOption completionOption, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpRequestMessage message, Object userState, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.SendAsync[T](HttpMethod method, IEnumerable`1 additionalHeaders, Guid locationId, Object routeValues, ApiResourceVersion version, HttpContent content, IEnumerable`1 queryParameters, Object userState, CancellationToken cancellationToken)
   at Azure.Sdk.Tools.NotificationConfiguration.Services.AzureDevOpsService.GetDescriptorForPrincipal(String userPrincipal) in /mnt/vss/_work/1/s/tools/identity-resolution/Services/AzureDevOpsService.cs:line 232
   at Azure.Sdk.Tools.NotificationConfiguration.NotificationConfigurator.SyncTeamWithCodeownersFile(BuildDefinition buildDefinition, WebApiTeam team, GitHubToAADConverter gitHubToAADConverter, Boolean persistChanges) in /mnt/vss/_work/1/s/tools/notification-configuration/notification-creator/NotificationConfigurator.cs:line 202
   at Azure.Sdk.Tools.NotificationConfiguration.NotificationConfigurator.EnsureTeamExists(BuildDefinition pipeline, TeamPurpose purpose, IEnumerable`1 teams, GitHubToAADConverter gitHubToAADConverter, Boolean persistChanges) in /mnt/vss/_work/1/s/tools/notification-configuration/notification-creator/NotificationConfigurator.cs:line 171
   at Azure.Sdk.Tools.NotificationConfiguration.NotificationConfigurator.ConfigureNotifications(String projectName, String projectPath, GitHubToAADConverter gitHubToAADConverter, Boolean persistChanges, PipelineSelectionStrategy strategy) in /mnt/vss/_work/1/s/tools/notification-configuration/notification-creator/NotificationConfigurator.cs:line 53
   at Azure.Sdk.Tools.NotificationConfiguration.Program.Main(String organization, String project, String pathPrefix, PipelineSelectionStrategy selectionStrategy, Boolean dryRun) in /mnt/vss/_work/1/s/tools/notification-configuration/notification-creator/Program.cs:line 67
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass2_0.<<InvokeAsync>b__0>d.MoveNext()
```

From a quick investigation this seems like it might be a breaking change on the ADO server side as we haven't change anything on our side to account for this error.

The failing call is at [CreateUserAsync](https://github.com/Azure/azure-sdk-tools/blob/main/tools/identity-resolution/Services/AzureDevOpsService.cs#L232) for some reason the service no longer likes our GraphUserPrincipalNameCreationContext payload.

**Comment by weshaggard** [comment]
Well seems like the service has been fixed with the latest run https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4008180&view=logs&j=f2ee0415-d5cb-5e2e-67d5-dd79ca5661b0&t=46a932f5-b02b-5d65-82b3-d219e9d05996. I'll keep an eye on this but for now closing.
