### ISSUE TITLE
[tsp-client] tsp client fails to clean TempTypeSpecFiles

### ISSUE THREAD

**Issue by dolauli** [Azure/azure-sdk-tools#8771]
emitter-package.json is as below.
```
{
    "main": "dist/src/index.js",
    "dependencies": {
      "@azure-tools/typespec-powershell": "0.0.x",
      "@azure-tools/typespec-azure-core": "0.44.0",
      "@azure-tools/typespec-azure-resource-manager": "0.44.0",
      "@azure-tools/typespec-client-generator-core": "0.44.2",
      "@typespec/compiler": "0.58.1",
      "@typespec/http": "0.58.0",
      "@typespec/openapi": "0.58.0",
      "@typespec/openapi3": "0.58.0",
      "@typespec/rest": "0.58.0",
      "@typespec/versioning": "0.58.0"
    }
}
```

The issue could be reproduced by running following command.
```
tsp-client init -c
https://github.com/dolauli/azure-rest-api-specs/blob/82a148896900c9bf89693d8dadea6a4acca5bf5c/specification/sphere/Sphere.Management/tspconfig.yaml
```

![image](https://github.com/user-attachments/assets/72339804-3b5a-4089-bbb3-313fa41f44e1)

**Comment by catalinaperalta** [comment]
Where there any updates to your emitter recently? I can't get the same error, I'm seeing this output now: 
```
C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@autorest\powershell\dist\plugins\llcsharp-v2.js - Error: ENOENT: no such file or directory, mkdir 'C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\generated\api'
    at mkdirSync (node:fs:1380:26)
    at TspHostImpl.writeFile (C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@autorest\powershell\dist\utils\tsp-host.js:28:32)
    at State.writeFile (C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@autorest\powershell\dist\utils\model-state.js:85:29)
    at C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@autorest\powershell\dist\plugins\llcsharp-v2.js:14:74
    at w (C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@azure-tools\codegen-csharp\dist\namespace.js:98:42)
    at ServiceNamespace.writeFiles (C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@azure-tools\codegen-csharp\dist\namespace.js:114:19)
    at C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@azure-tools\codegen-csharp\dist\project.js:24:64
    at Array.map (<anonymous>)
    at Object.pall (C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@azure-tools\codegen\dist\text-manipulation.js:150:30)
    at Project.writeFiles (C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@azure-tools\codegen-csharp\dist\project.js:24:25)/ENOENT: no such file or directory, mkdir 'C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\generated\api'      
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ENOENT: no such file or directory, mkdir 'C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\generated\api'
    at mkdirSync (node:fs:1380:26)
    at TspHostImpl.writeFile (C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@autorest\powershell\dist\utils\tsp-host.js:28:32)
    at State.writeFile (C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@autorest\powershell\dist\utils\model-state.js:85:29)
    at C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@autorest\powershell\dist\plugins\llcsharp-v2.js:14:74
    at w (C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@azure-tools\codegen-csharp\dist\namespace.js:98:42)
    at ServiceNamespace.writeFiles (C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@azure-tools\codegen-csharp\dist\namespace.js:114:19)
    at C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@azure-tools\codegen-csharp\dist\project.js:24:64
    at Array.map (<anonymous>)
    at Object.pall (C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@azure-tools\codegen\dist\text-manipulation.js:150:30)
    at Project.writeFiles (C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@azure-tools\codegen-csharp\dist\project.js:24:25) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: 'C:\\Users\\caperal\\repos\\testpwsh\\sdk\\spheremanager\\spheremanager\\C:\\Users\\caperal\\repos\\testpwsh\\sdk\\spheremanager\\spheremanager\\generated\\api'
}

Node.js v20.11.0
```

The first lines of the error seem to be pointing to an issue in one of the emitter's files: 
```
C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@autorest\powershell\dist\plugins\llcsharp-v2.js - Error: ENOENT: no such file or directory, mkdir 'C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\generated\api'
    at mkdirSync (node:fs:1380:26)
    at TspHostImpl.writeFile (C:\Users\caperal\repos\testpwsh\sdk\spheremanager\spheremanager\TempTypeSpecFiles\node_modules\@autorest\powershell\dist\utils\tsp-host.js:28:32)
```

**Comment by dolauli** [comment]
I did not change the emitter, but I changed a dependency -- autorest/powershell. I think you may pin autorest/powershell to an old version by adding `"@autorest/powershell": "4.0.703"` in emitter-package.json.

**Comment by catalinaperalta** [comment]
After you updated your dependency are you still running into the first issue or are you seeing something like the error I shared? I wonder if the emitter is kicking off separate processes that conflict with what tsp-client is doing.

**Comment by dolauli** [comment]
You've jogged my memory. Let me review my code.

**Comment by dolauli** [comment]
My bad. Proved to be a bug in my emitter. I forget to add `await` when calling an `async` function. tsp-client works fine after I fixed my issue.
