### ISSUE TITLE
[JS SDK automation] Changelog Generation Failure

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#9100]
**Description**
The JS SDK automation failed during the changelog generation step with the following error. This issue is unrelated to the changes in this [spec PR](https://github.com/Azure/azure-rest-api-specs/pull/30858/files)

The build log can be found at [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4200800&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2)
```powershell
[automation_generate.sh] [ERROR]: Failed to generate changelog: ENOENT: no such file or directory, scandir '/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/healthinsights/azurehealthinsightsradiologyinsights-rest/review'.
08:26:36.401 cmdout 	[automation_generate.sh] [ERROR]: Failed to build typespec project: "specification/ai/HealthInsights/HealthInsights.RadiologyInsights":
08:26:36.401 cmdout 	[automation_generate.sh] Err: Error: ENOENT: no such file or directory, scandir '/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/healthinsights/azurehealthinsightsradiologyinsights-rest/review'
08:26:36.401 cmdout 	[automation_generate.sh] Stderr: "undefined"
08:26:36.402 cmdout 	[automation_generate.sh] Stdout: "undefined"
08:26:36.402 cmdout 	[automation_generate.sh] ErrorStack: "Error: ENOENT: no such file or directory, scandir '/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/healthinsights/azurehealthinsightsradiologyinsights-rest/review'
08:26:36.403 cmdout 	[automation_generate.sh]     at Object.readdirSync (node:fs:1525:3)
08:26:36.403 cmdout 	[automation_generate.sh]     at getApiReviewPath (/opt/hostedtoolcache/node/18.20.4/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/common/utils.js:105:76)
08:26:36.403 cmdout 	[automation_generate.sh]     at generateChangelog (/opt/hostedtoolcache/node/18.20.4/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/llc/utils/generateChangelog.js:70:69)
08:26:36.403 cmdout 	[automation_generate.sh]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
08:26:36.403 cmdout 	[automation_generate.sh]     at async generateRLCInPipeline (/opt/hostedtoolcache/node/18.20.4/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/llc/generateRLCInPipeline/generateRLCInPipeline.js:222:13)
08:26:36.403 cmdout 	[automation_generate.sh]     at async automationGenerateInPipeline (/opt/hostedtoolcache/node/18.20.4/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/autoGenerateInPipeline.js:38:17)".
```

@qiaozha , can you have a look if this is a known issue?

**Comment by raych1** [comment]
CC: @wanlwanl

**Comment by wanlwanl** [comment]
At least the ts config is incorrect.
Commented in PR.
@raych1

**Comment by wanlwanl** [comment]
Looks like the tspconfig is incorrect, please create a new pr to generate js sdk @kazrael2119

**Comment by wanlwanl** [comment]
close for user config error
