### ISSUE TITLE
tsp-client, TypeError in 0.13.3

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-tools#9345]
Run `tsp-client update` under https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/healthinsights/azure-health-insights-clinicalmatching

0.13.0 is good

<-- update, the cause seems to be the latest compiler; maybe compatibility problem between the 2 libs -- tsp-client sending `undefined` that previously get ignored but now get thrown?

```
Using output directory 'C:/github/azure-sdk-for-java/sdk/healthinsights/azure-health-insights-clinicalmatching'

888                                      888 d8b                   888
888                                      888 Y8P                   888
888                                      888                       888
888888 .d8888b  88888b.          .d8888b 888 888  .d88b.  88888b.  888888
888    88K      888 "88b        d88P"    888 888 d8P  Y8b 888 "88b 888
888    "Y8888b. 888  888 888888 888      888 888 88888888 888  888 888
Y88b.       X88 888 d88P        Y88b.    888 888 Y8b.     888  888 Y88b.
 "Y888  88888P' 88888P"          "Y8888P 888 888  "Y8888  888  888  "Y888
                888
                888
                888

0.13.0
Processing additional directory: specification/ai/HealthInsights/HealthInsights.OpenAPI
Processing additional directory: specification/ai/HealthInsights/HealthInsights.Common
Syncing additional directory: specification/ai/HealthInsights/HealthInsights.OpenAPI
Syncing additional directory: specification/ai/HealthInsights/HealthInsights.Common
Found emitter package @azure-tools/typespec-java@0.22.1
Installing dependencies from npm...

added 95 packages, and audited 96 packages in 2s

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Resolved path: C:/github/azure-sdk-for-java/sdk/healthinsights/azure-health-insights-clinicalmatching/TempTypeSpecFiles/node_modules/@typespec/compiler
Compiling tsp using @azure-tools/typespec-java...
Diagnostics were reported during compilation. Use the `--debug` flag to see if there is warning diagnostic output.
generation complete
```

0.13.3 gives error

```
Using output directory 'C:/github/azure-sdk-for-java/sdk/healthinsights/azure-health-insights-clinicalmatching'

888                                      888 d8b                   888
888                                      888 Y8P                   888
888                                      888                       888
888888 .d8888b  88888b.          .d8888b 888 888  .d88b.  88888b.  888888
888    88K      888 "88b        d88P"    888 888 d8P  Y8b 888 "88b 888
888    "Y8888b. 888  888 888888 888      888 888 88888888 888  888 888
Y88b.       X88 888 d88P        Y88b.    888 888 Y8b.     888  888 Y88b.
 "Y888  88888P' 88888P"          "Y8888P 888 888  "Y8888  888  888  "Y888
                888
                888
                888

0.13.3
Processing additional directory: specification/ai/HealthInsights/HealthInsights.OpenAPI
Processing additional directory: specification/ai/HealthInsights/HealthInsights.Common
Syncing additional directory: specification/ai/HealthInsights/HealthInsights.OpenAPI
Syncing additional directory: specification/ai/HealthInsights/HealthInsights.Common
Found emitter package @azure-tools/typespec-java@0.22.1
Installing dependencies from npm...

added 95 packages, and audited 96 packages in 2s

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Resolved path: C:/github/azure-sdk-for-java/sdk/healthinsights/azure-health-insights-clinicalmatching/TempTypeSpecFiles/node_modules/@typespec/compiler
Compiling tsp using @azure-tools/typespec-java...
Diagnostics were reported during compilation. Use the `--debug` flag to see if there is warning diagnostic output.
update

Sync and generate from a TypeSpec project

Options:
  -d, --debug            Enable debug logging                          [boolean]
  -o, --output-dir       Specify an alternate output directory for the generated
                         files.                          [string] [default: "."]
  -y, --no-prompt        Skip any interactive prompts.                 [boolean]
      --help             Show help                                     [boolean]
      --repo             Repository where the project is defined        [string]
      --commit           Commit hash to be used                         [string]
      --tsp-config       Path to tspconfig.yaml                         [string]
      --local-spec-repo  Path to local spec repo                        [string]
      --emitter-options  The options to pass to the emitter             [string]
      --save-inputs      Don't clean up the temp directory after generation
                                                                       [boolean]
  -v, --version          Show version number                           [boolean]

TypeError: Cannot read properties of undefined (reading 'node')
    at getDiagnosticTemplateInstantitationTrace (file:///C:/Users/weidxu/AppData/Roaming/npm/node_modules/@azure-tools/typespec-client-generator-cli/node_modules/@typespec/compiler/dist/src/core/diagnostics.js:87:36)
    at getRelatedLocations (file:///C:/Users/weidxu/AppData/Roaming/npm/node_modules/@azure-tools/typespec-client-generator-cli/node_modules/@typespec/compiler/dist/src/core/diagnostics.js:36:12)
    at formatDiagnostic (file:///C:/Users/weidxu/AppData/Roaming/npm/node_modules/@azure-tools/typespec-client-generator-cli/node_modules/@typespec/compiler/dist/src/core/diagnostics.js:32:18)
    at compileTsp (file:///C:/Users/weidxu/AppData/Roaming/npm/node_modules/@azure-tools/typespec-client-generator-cli/dist/typespec.js:98:30)
    at async generateCommand (file:///C:/Users/weidxu/AppData/Roaming/npm/node_modules/@azure-tools/typespec-client-generator-cli/dist/commands.js:238:21)
    at async updateCommand (file:///C:/Users/weidxu/AppData/Roaming/npm/node_modules/@azure-tools/typespec-client-generator-cli/dist/commands.js:292:5)
    at async Object.handler (file:///C:/Users/weidxu/AppData/Roaming/npm/node_modules/@azure-tools/typespec-client-generator-cli/dist/index.js:151:5)
```

**Comment by archerzz** [comment]
It is blocking .NET team to publish changes to `azure-sdk-for-net`. See the error log: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4308242&view=logs&j=d731b843-2b38-5e88-bb49-012fa10bc295&t=f10e5fff-58d7-557f-26b5-c063ad57cd53&l=594

Moreover, it seems like the generation has been triggered twice. The 1st run was successful. Is that a bug?

**Comment by archerzz** [comment]
Not sure if it's related, I found the `tsp-client` seems always pull in latest version of tsp (e.g. `0.62`. But in our case, the emitter is based on last second version (`0.61.2`). There were warnings if run `tsp-client --debug`:
```
warning incompatible-library: Multiple versions of "@typespec/versioning" library were loaded:
  - Version: "0.61.0" installed at "C:/Users/mingzhehuang/workspaces/azure/azure-sdk-for-net/sdk/easm/Azure.Analytics.Defender.Easm/TempTypeSpecFiles/node_modules/@typespec/versioning"
  - Version: "0.62.0" installed at "C:/.tools/.npm-global/node_modules/@azure-tools/typespec-client-generator-cli/node_modules/@typespec/versioning"
warning incompatible-library: Multiple versions of "@typespec/http" library were loaded:
  - Version: "0.61.0" installed at "C:/Users/mingzhehuang/workspaces/azure/azure-sdk-for-net/sdk/easm/Azure.Analytics.Defender.Easm/TempTypeSpecFiles/node_modules/@typespec/http"
  - Version: "0.62.0" installed at "C:/.tools/.npm-global/node_modules/@azure-tools/typespec-client-generator-cli/node_modules/@typespec/http"
warning incompatible-library: Multiple versions of "@azure-tools/typespec-client-generator-core" library were loaded:
  - Version: "0.47.4" installed at "C:/Users/mingzhehuang/workspaces/azure/azure-sdk-for-net/sdk/easm/Azure.Analytics.Defender.Easm/TempTypeSpecFiles/node_modules/@azure-tools/typespec-client-generator-core"
  - Version: "0.48.1" installed at "C:/.tools/.npm-global/node_modules/@azure-tools/typespec-client-generator-cli/node_modules/@azure-tools/typespec-client-generator-core"
warning incompatible-library: Multiple versions of "@azure-tools/typespec-azure-core" library were loaded:
  - Version: "0.47.0" installed at "C:/Users/mingzhehuang/workspaces/azure/azure-sdk-for-net/sdk/easm/Azure.Analytics.Defender.Easm/TempTypeSpecFiles/node_modules/@azure-tools/typespec-azure-core"
  - Version: "0.48.0" installed at "C:/.tools/.npm-global/node_modules/@azure-tools/typespec-client-generator-cli/node_modules/@azure-tools/typespec-azure-core"
warning incompatible-library: Multiple versions of "@typespec/rest" library were loaded:
  - Version: "0.61.0" installed at "C:/Users/mingzhehuang/workspaces/azure/azure-sdk-for-net/sdk/easm/Azure.Analytics.Defender.Easm/TempTypeSpecFiles/node_modules/@typespec/rest"
  - Version: "0.62.0" installed at "C:/.tools/.npm-global/node_modules/@azure-tools/typespec-client-generator-cli/node_modules/@typespec/rest"
C:/Users/mingzhehuang/workspaces/azure/azure-sdk-for-net/sdk/easm/Azure.Analytics.Defender.Easm/TempTypeSpecFiles/Easm/models.tsp:168:7 - warning @azure-tools/typespec-azure-core/no-string-discriminator: Use an extensible union instead of a plain string (ex: `union PetKind { cat: "cat", dog: "dog", string };`)
C:/Users/mingzhehuang/workspaces/azure/azure-sdk-for-net/sdk/easm/Azure.Analytics.Defender.Easm/TempTypeSpecFiles/Easm/models.tsp:409:7 - warning @azure-tools/typespec-azure-core/no-string-discriminator: Use an extensible union instead of a plain string (ex: `union PetKind { cat: "cat", dog: "dog", string };`)
C:/Users/mingzhehuang/workspaces/azure/azure-sdk-for-net/sdk/easm/Azure.Analytics.Defender.Easm/TempTypeSpecFiles/Easm/models.tsp:392:7 - warning @azure-tools/typespec-azure-core/no-string-discriminator: Use an extensible union instead of a plain string (ex: `union PetKind { cat: "cat", dog: "dog", string };`)
```

**Comment by pshao25** [comment]
@weidongxu-microsoft  Why do you think it is tsp-client issue? There is no code change related to `update` between 0.13.0 and 0.13.3. From call stack it is more like a compiler issue.

**Comment by weidongxu-microsoft** [comment]
It probably about the local dependency.

After I install 0.13.3, rolling it back to 0.13.0 seems won't work again.

Maybe the cause is the compiler lib.

**Comment by pshao25** [comment]
Probably it is better to ask TypeSpec team take a look first.

**Comment by archerzz** [comment]
> It probably about the local dependency.
> 
> After I install 0.13.3, rolling it back to 0.13.0 seems won't work again.
> 
> Maybe the cause is the compiler lib.

`package.json` of `tsp-client` is like below:
https://github.com/Azure/azure-sdk-tools/blob/59d869dd3abdbc1aa6d8d3935f9c52fe3ba6d37a/tools/tsp-client/package.json#L69

So, in pipeline, `npm ci` will always install the latest version of compiler.

**Comment by archerzz** [comment]
I think maybe `tsp-client` should honor the versions defined in the `package.json` of the individual emitters?

**Comment by weidongxu-microsoft** [comment]
> I think maybe `tsp-client` should honor the versions defined in the `package.json` of the individual emitters?

This probably won't work in current upgrade version scenario... We do upgrade emitter-package.json to compiler 0.62.

**Comment by pshao25** [comment]
> I think maybe `tsp-client` should honor the versions defined in the `package.json` of the individual emitters?

As you pointed out, it is peerdependency, so it still loads the version specified in the emitter-package-locked.json.

**Comment by archerzz** [comment]
> > I think maybe `tsp-client` should honor the versions defined in the `package.json` of the individual emitters?
> 
> As you pointed out, it is peerdependency, so it still loads the version specified in the emitter-package-locked.json.

It's not. See the screen snapshot, it's using the bundled one.
 ![Image](https://github.com/user-attachments/assets/77c5a224-7097-4a2b-9516-55613c450e38)

**Comment by weidongxu-microsoft** [comment]
close for now.

the cause more likely under compiler 0.62
