### ISSUE TITLE
[MONITOR-SPEC-PR] User error on tspconfig - failed to set groups of options for a specific client type, client type inference should be improved 

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-tools#9520]
**Description:**
```
10:02:54.858 cmdout 	[automation_generate.sh] [INFO]: Start to generate changelog and bump version in sdk/eventgrid/eventgrid
10:02:54.859 cmdout 	[automation_generate.sh] [INFO]: SDK type 'ModularClient' is detected in '/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/eventgrid/eventgrid'.
10:02:54.878 cmdout 	[automation_generate.sh] [WARN]: Failed to find extactly one REST client in pattern '/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/eventgrid/eventgrid/src/api/*Context.ts', got ''.
10:02:54.879 cmdout 	[automation_generate.sh] [WARN]: Failed to find extactly one REST client in pattern '/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/eventgrid/eventgrid/src/rest/*Client.ts', got ''.
10:02:54.879 cmdout 	[automation_generate.sh] [ERROR]: Failed to build typespec project: "specification/eventgrid/Azure.Messaging.EventGrid":
10:02:54.879 cmdout 	[automation_generate.sh] Err: Error: Expected 1 'parameters.ts' file, but found '' in '/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/eventgrid/eventgrid/src/rest'.
10:02:54.879 cmdout 	[automation_generate.sh] Stderr: "undefined"
10:02:54.879 cmdout 	[automation_generate.sh] Stdout: "undefined"
10:02:54.879 cmdout 	[automation_generate.sh] ErrorStack: "Error: Expected 1 'parameters.ts' file, but found '' in '/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/eventgrid/eventgrid/src/rest'.
10:02:54.879 cmdout 	[automation_generate.sh]     at findParametersPath (/opt/hostedtoolcache/node/18.20.5/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/xlc/apiVersion/utils.js:117:15)
10:02:54.879 cmdout 	[automation_generate.sh]     at getApiVersionTypeFromOperations (/opt/hostedtoolcache/node/18.20.5/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/xlc/apiVersion/utils.js:135:22)
10:02:54.879 cmdout 	[automation_generate.sh]     at Object.getApiVersionType (/opt/hostedtoolcache/node/18.20.5/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/mlc/apiVersion/apiVersionTypeExtractor.js:16:76)
10:02:54.880 cmdout 	[automation_generate.sh]     at async getApiVersionType (/opt/hostedtoolcache/node/18.20.5/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/xlc/apiVersion/apiVersionTypeExtractor.js:14:20)
10:02:54.880 cmdout 	[automation_generate.sh]     at async generateChangelogAndBumpVersion (/opt/hostedtoolcache/node/18.20.5/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/common/changlog/automaticGenerateChangeLogAndBumpVersion.js:22:21)
10:02:54.880 cmdout 	[automation_generate.sh]     at async generateRLCInPipeline (/opt/hostedtoolcache/node/18.20.5/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/llc/generateRLCInPipeline/generateRLCInPipeline.js:221:31)
10:02:54.880 cmdout 	[automation_generate.sh]     at async automationGenerateInPipeline (/opt/hostedtoolcache/node/18.20.5/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/autoGenerateInPipeline.js:38:17)".
10:02:54.880 cmdout 	[automation_generate.sh] [ERROR]: Please check out https://github.com/Azure/autorest.typescript/blob/main/packages/typespec-ts/CONTRIBUTING.md#how-to-debug to troubleshoot the issue.
10:02:54.880 cmderr 	[automation_generate.sh] ls: no such file or directory: /mnt/vss/_work/1/s/azure-sdk-for-js/sdk/eventgrid/eventgrid/src/rest
10:02:54.880 cmdout 	[automation_generate.sh] [ERROR]: Failed to generate SDK for package '@azure/eventgrid' due to Error: Expected 1 'parameters.ts' file, but found '' in '/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/eventgrid/eventgrid/src/rest'.
10:02:54.880 cmdout 	[automation_generate.sh]     at findParametersPath (/opt/hostedtoolcache/node/18.20.5/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/xlc/apiVersion/utils.js:117:15)
10:02:54.880 cmdout 	[automation_generate.sh]     at getApiVersionTypeFromOperations (/opt/hostedtoolcache/node/18.20.5/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/xlc/apiVersion/utils.js:135:22)
10:02:54.881 cmdout 	[automation_generate.sh]     at Object.getApiVersionType (/opt/hostedtoolcache/node/18.20.5/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/mlc/apiVersion/apiVersionTypeExtractor.js:16:76)
10:02:54.881 cmdout 	[automation_generate.sh]     at async getApiVersionType (/opt/hostedtoolcache/node/18.20.5/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/xlc/apiVersion/apiVersionTypeExtractor.js:14:20)
10:02:54.881 cmdout 	[automation_generate.sh]     at async generateChangelogAndBumpVersion (/opt/hostedtoolcache/node/18.20.5/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/common/changlog/automaticGenerateChangeLogAndBumpVersion.js:22:21)
10:02:54.881 cmdout 	[automation_generate.sh]     at async generateRLCInPipeline (/opt/hostedtoolcache/node/18.20.5/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/llc/generateRLCInPipeline/generateRLCInPipeline.js:221:31)
10:02:54.881 cmdout 	[automation_generate.sh]     at async automationGenerateInPipeline (/opt/hostedtoolcache/node/18.20.5/x64/lib/node_modules/@azure-tools/js-sdk-release-tools/dist/autoGenerateInPipeline.js:38:17).
10:02:54.881 cmdout 	[automation_generate.sh] [ERROR]: Please review the detail errors for potential fixes.
10:02:54.881 cmdout 	[automation_generate.sh] [ERROR]: If the issue persists, contact the support channel at https://aka.ms/azsdk/js-teams-channel and include this spec pull request.
10:02:54.881 cmdout 	[automation_generate.sh] [INFO]: Start to rename '/mnt/vss/_work/1/s/node_modules_backup' to '/mnt/vss/_work/1/s/node_modules'.
10:02:54.881 cmdout 	[automation_generate.sh] [ERROR]: Expected 1 'parameters.ts' file, but found '' in '/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/eventgrid/eventgrid/src/rest'.
10:02:54.908 error C 	Script return with result [failed] code [1] signal [null] cwd [azure-sdk-for-js]: sh .scripts/automation_generate.sh
10:02:54.908 endsection 	Call generateScript
```

**Additional context:**
link1:
https://github.com/Azure/azure-rest-api-specs/pull/31801/checks?check_run_id=34157982485
link2:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4397070&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=6584

**Comment by wanlwanl** [comment]
Looks like the js emitter changes the generated content. The current supported path is: https://github.com/Azure/azure-sdk-tools/blob/45fc16d7597648b49258ddeb90ed202d39387c3a/tools/js-sdk-release-tools/src/mlc/apiVersion/apiVersionTypeExtractor.ts#L16

We need to update js-sdk-release-tool based on https://github.com/azure-sdk/azure-sdk-for-js/pull/13083/files

**Comment by jianingwang123** [comment]
related： https://github.com/Azure/autorest.typescript/issues/3067

**Comment by lirenhe** [comment]
Close it as not planned.
