### ISSUE TITLE
[MONITOR-SPEC-PR] user error and Nuget library issue lead to Emitter "@azure-tools/typespec-csharp" crashed

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-tools#9555]
Section1:
**Description:**
error `System.InvalidOperationException: Unable to find a model or framework type that corresponds to Azure.AI.DocumentIntelligence.DocumentFieldDictionary` lead to
`ExternalError: Emitter "@azure-tools/typespec-csharp" crashed!`

link: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4404510&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=225
```
11:30:55.261 cmdout 	[.Net] Resolved path: /mnt/vss/_work/1/s/azure-sdk-for-net/sdk/documentintelligence/Azure.AI.DocumentIntelligence/TempTypeSpecFiles/node_modules/@typespec/compiler
11:30:55.441 cmdout 	[.Net] Compiling tsp using @azure-tools/typespec-csharp...
11:31:01.556 cmderr 	[.Net] System.InvalidOperationException: Unable to find a model or framework type that corresponds to Azure.AI.DocumentIntelligence.DocumentFieldDictionary
11:31:01.556 cmderr 	[.Net]    at AutoRest.CSharp.Generation.Types.TypeFactory.CreateType(ITypeSymbol symbol) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Types\TypeFactory.cs:line 186
11:31:01.557 cmderr 	[.Net]    at AutoRest.CSharp.Output.Builders.BuilderHelpers.GetTypeFromExisting(ISymbol existingMember, CSharpType defaultType, TypeFactory typeFactory) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Builders\BuilderHelpers.cs:line 225
11:31:01.557 cmderr 	[.Net]    at AutoRest.CSharp.Output.Models.Types.ModelTypeProviderFields.CreateFieldFromExisting(ISymbol existingMember, CSharpType originalType, ValueExpression initializationValue, SerializationFormat serializationFormat, TypeFactory typeFactory, Boolean isRequired, Boolean optionalViaNullability) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProviderFields.cs:line 293
11:31:01.558 cmderr 	[.Net]    at AutoRest.CSharp.Output.Models.Types.ModelTypeProviderFields..ctor(IReadOnlyList`1 properties, String modelName, InputModelTypeUsage inputModelUsage, TypeFactory typeFactory, ModelTypeMapping modelTypeMapping, InputType additionalPropertiesValueType, Boolean isStruct, Boolean isPropertyBag) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProviderFields.cs:line 57
11:31:01.558 cmderr 	[.Net]    at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.get_Fields() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 51
11:31:01.558 cmderr 	[.Net]    at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.EnsureAdditionalPropertiesProperty() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 58
11:31:01.558 cmderr 	[.Net]    at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.get_AdditionalPropertiesProperty() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 55
11:31:01.558 cmderr 	[.Net]    at AutoRest.CSharp.Output.Models.Types.ModelTypeProvider.get_RawDataField() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Output\Models\Types\ModelTypeProvider.cs:line 76
11:31:01.559 cmderr 	[.Net]    at AutoRest.CSharp.Generation.Writers.ModelWriter.WritePrivateRawDataField(CodeWriter writer, ObjectType schema) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\ModelWriter.cs:line 102
11:31:01.559 cmderr 	[.Net]    at AutoRest.CSharp.Generation.Writers.ModelWriter.WriteObjectSchema(CodeWriter writer, ObjectType schema) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\ModelWriter.cs:line 75
11:31:01.559 cmderr 	[.Net]    at AutoRest.CSharp.Generation.Writers.ModelWriter.WriteModel(CodeWriter writer, TypeProvider model) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Generation\Writers\ModelWriter.cs:line 26
11:31:01.559 cmderr 	[.Net]    at AutoRest.CSharp.AutoRest.Plugins.LowLevelTarget.ExecuteAsync(GeneratedCodeWorkspace project, InputNamespace inputNamespace, SourceInputModel sourceInputModel, Boolean isTspInput) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\LowLevel\AutoRest\LowLevelTarget.cs:line 26
11:31:01.560 cmderr 	[.Net]    at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(InputNamespace rootNamespace) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 92
11:31:01.560 cmderr 	[.Net]    at AutoRest.CSharp.AutoRest.Communication.StandaloneGeneratorRunner.RunAsync(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\StandaloneGeneratorRunner.cs:line 62
11:31:01.560 cmderr 	[.Net]    at AutoRest.CSharp.Program.Run(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 47
11:31:01.560 cmderr 	[.Net]    at AutoRest.CSharp.Program.<>c.<<Main>b__2_0>d.MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 29
11:31:01.561 cmderr 	[.Net] --- End of stack trace from previous location ---
11:31:01.561 cmderr 	[.Net]    at AutoRest.CSharp.Program.Main(String[] args) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 26
11:31:01.561 cmderr 	[.Net]    at AutoRest.CSharp.Program.<Main>(String[] args)
```

Section2:
**Description:**
error `System.InvalidOperationException: Can't find Baseline contract assembly (Azure.ResourceManager.StandbyPool@1.0.0) from Nuget Global Package Folder` lead to
`ExternalError: Emitter "@azure-tools/typespec-csharp" crashed!`

link1: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4416322&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=213
link2: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4422805&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=181
link3: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4467263&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=293
link4: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4473023&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=182

```
08:47:55.859 cmderr 	[.Net] System.InvalidOperationException: Can't find Baseline contract assembly (Azure.ResourceManager.StandbyPool@1.0.0) from Nuget Global Package Folder at /home/cloudtest/.nuget/packages/azure.resourcemanager.standbypool/1.0.0/lib/netstandard2.0/Azure.ResourceManager.StandbyPool.dll. Please make sure the baseline nuget package has been installed properly
08:47:55.860 cmderr 	[.Net]    at AutoRest.CSharp.Input.Source.SourceInputModel.LoadBaselineContract() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Input\Source\SourceInputModel.cs:line 164
08:47:55.860 cmderr 	[.Net]    at AutoRest.CSharp.Input.Source.SourceInputModel..ctor(Compilation customization, CompilationInput existingCompilation) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\Input\Source\SourceInputModel.cs:line 32
08:47:55.860 cmderr 	[.Net]    at AutoRest.CSharp.AutoRest.Plugins.CSharpGen.ExecuteAsync(InputNamespace rootNamespace) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Plugins\CSharpGen.cs:line 82
08:47:55.860 cmderr 	[.Net]    at AutoRest.CSharp.AutoRest.Communication.StandaloneGeneratorRunner.RunAsync(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Common\AutoRest\Communication\StandaloneGeneratorRunner.cs:line 62
08:47:55.860 cmderr 	[.Net]    at AutoRest.CSharp.Program.Run(CommandLineOptions options) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 47
08:47:55.860 cmderr 	[.Net]    at AutoRest.CSharp.Program.<>c.<<Main>b__2_0>d.MoveNext() in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 29
08:47:55.860 cmderr 	[.Net] --- End of stack trace from previous location ---
08:47:55.860 cmderr 	[.Net]    at AutoRest.CSharp.Program.Main(String[] args) in D:\a\_work\1\s\autorest.csharp\src\AutoRest.CSharp\Program.cs:line 26
08:47:55.861 cmderr 	[.Net]    at AutoRest.CSharp.Program.<Main>(String[] args)
```

**Comment by wanlwanl** [comment]
@chunyu3 could you take a look at the crash?

**Comment by jianingwang123** [comment]
Section1 seems to be tsp code error, Section2 seems to be Nuget library problems caused by internal or network reasons.
