### ISSUE TITLE
[MONITOR-SPEC-PR] Unable to complete customization

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-tools#9561]
**Description:**
(java)Failed to generate client.

**Additional context:**
section1:
```
11:29:38.484 cmdout 	[Java-Sdk-Automation] Resolved path: /mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence/TempTypeSpecFiles/node_modules/@typespec/compiler
11:29:38.669 cmdout 	[Java-Sdk-Automation] Compiling tsp using @azure-tools/typespec-java...
11:29:38.878 cmdout 	[Java-Sdk-Automation] Compiler options: {"outputDir":"/mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence","config":"/mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence/TempTypeSpecFiles/DocumentIntelligence/tspconfig.yaml","configFile":{"outputDir":"{cwd}/tsp-output","diagnostics":[],"projectRoot":"/mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence/TempTypeSpecFiles/DocumentIntelligence","file":{"kind":"yaml-script","file":{"text":"parameters:\n  \"service-dir\":\n    \"default\": \"sdk/documentintelligence\"\n\nemit:\n  - \"@azure-tools/typespec-autorest\"\n  # - \"@azure-tools/typespec-csharp\",\n  # - \"@azure-tools/typespec-python\",\n  # - \"@azure-tools/typespec-ts\"\nlinter:\n  extends:\n    - \"@azure-tools/typespec-azure-rulesets/data-plane\"\noptions:\n  \"@azure-tools/typespec-autorest\":\n    azure-resource-provider-folder: \"data-plane\"\n    emit-lro-options: \"none\"\n    emitter-output-dir: \"{project-root}/..\"\n    omit-unreachable-types: true\n    output-file: \"{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/DocumentIntelligence.json\"\n  \"@azure-tools/typespec-python\":\n    package-pprint-name: \"Azure AI Document Intelligence\"\n    package-dir: \"azure-ai-documentintelligence\"\n    package-name: \"{package-dir}\"\n    package-version: 1.0.0b2\n    flavor: azure\n    generate-test: true\n    generate-sample: true\n  \"@azure-tools/typespec-java\":\n    package-dir: \"azure-ai-documentintelligence\"\n    namespace: \"com.azure.ai.documentintelligence\"\n    enable-sync-stack: true\n    custom-types-subpackage: \"implementation.models\"\n    generate-tests: false\n    customization-class: customization/src/main/java/DocumentIntelligenceCustomizations.java\n    polling:\n      buildDocumentModel:\n        final-type: com.azure.ai.documentintelligence.models.DocumentModelDetails\n      buildClassifier:\n        final-type: com.azure.ai.documentintelligence.models.DocumentClassifierDetails\n      composeModel:\n        final-type: com.azure.ai.documentintelligence.models.DocumentModelDetails\n      copyModelTo:\n        final-type: com.azure.ai.documentintelligence.models.DocumentModelDetails\n    flavor: azure\n  \"@azure-tools/typespec-csharp\":\n    package-dir: \"Azure.AI.DocumentIntelligence\"\n    namespace: \"Azure.AI.DocumentIntelligence\"\n    model-namespace: false\n    flavor: azure\n  \"@azure-tools/typespec-ts\":\n    title: DocumentIntelligence\n    package-dir: \"ai-document-intelligence-rest\"\n    generateMetadata: true\n    generate-tests: false\n    packageDetails:\n      name: \"@azure-rest/ai-document-intelligence\"\n      description: \"Document Intelligence Rest Client\"\n      version: \"1.0.0\"\n    flavor: azure\n","path":"/mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence/TempTypeSpecFiles/DocumentIntelligence/tspconfig.yaml"},"value":{"parameters":{"service-dir":{"default":"sdk/documentintelligence"}},"emit":["@azure-tools/typespec-autorest"],"linter":{"extends":["@azure-tools/typespec-azure-rulesets/data-plane"]},"options":{"@azure-tools/typespec-autorest":{"azure-resource-provider-folder":"data-plane","emit-lro-options":"none","emitter-output-dir":"{project-root}/..","omit-unreachable-types":true,"output-file":"{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/DocumentIntelligence.json"},"@azure-tools/typespec-python":{"package-pprint-name":"Azure AI Document Intelligence","package-dir":"azure-ai-documentintelligence","package-name":"{package-dir}","package-version":"1.0.0b2","flavor":"azure","generate-test":true,"generate-sample":true},"@azure-tools/typespec-java":{"package-dir":"azure-ai-documentintelligence","namespace":"com.azure.ai.documentintelligence","enable-sync-stack":true,"custom-types-subpackage":"implementation.models","generate-tests":false,"customization-class":"customization/src/main/java/DocumentIntelligenceCustomizations.java","polling":{"buildDocumentModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"buildClassifier":{"final-type":"com.azure.ai.documentintelligence.models.DocumentClassifierDetails"},"composeModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"copyModelTo":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"}},"flavor":"azure"},"@azure-tools/typespec-csharp":{"package-dir":"Azure.AI.DocumentIntelligence","namespace":"Azure.AI.DocumentIntelligence","model-namespace":false,"flavor":"azure"},"@azure-tools/typespec-ts":{"title":"DocumentIntelligence","package-dir":"ai-document-intelligence-rest","generateMetadata":true,"generate-tests":false,"packageDetails":{"name":"@azure-rest/ai-document-intelligence","description":"Document Intelligence Rest Client","version":"1.0.0"},"flavor":"azure"}}},"doc":{"parameters":{"service-dir":{"default":"sdk/documentintelligence"}},"emit":["@azure-tools/typespec-autorest"],"linter":{"extends":["@azure-tools/typespec-azure-rulesets/data-plane"]},"options":{"@azure-tools/typespec-autorest":{"azure-resource-provider-folder":"data-plane","emit-lro-options":"none","emitter-output-dir":"{project-root}/..","omit-unreachable-types":true,"output-file":"{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/DocumentIntelligence.json"},"@azure-tools/typespec-python":{"package-pprint-name":"Azure AI Document Intelligence","package-dir":"azure-ai-documentintelligence","package-name":"{package-dir}","package-version":"1.0.0b2","flavor":"azure","generate-test":true,"generate-sample":true},"@azure-tools/typespec-java":{"package-dir":"azure-ai-documentintelligence","namespace":"com.azure.ai.documentintelligence","enable-sync-stack":true,"custom-types-subpackage":"implementation.models","generate-tests":false,"customization-class":"customization/src/main/java/DocumentIntelligenceCustomizations.java","polling":{"buildDocumentModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"buildClassifier":{"final-type":"com.azure.ai.documentintelligence.models.DocumentClassifierDetails"},"composeModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"copyModelTo":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"}},"flavor":"azure"},"@azure-tools/typespec-csharp":{"package-dir":"Azure.AI.DocumentIntelligence","namespace":"Azure.AI.DocumentIntelligence","model-namespace":false,"flavor":"azure"},"@azure-tools/typespec-ts":{"title":"DocumentIntelligence","package-dir":"ai-document-intelligence-rest","generateMetadata":true,"generate-tests":false,"packageDetails":{"name":"@azure-rest/ai-document-intelligence","description":"Document Intelligence Rest Client","version":"1.0.0"},"flavor":"azure"}}}},"filename":"/mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence/TempTypeSpecFiles/DocumentIntelligence/tspconfig.yaml","parameters":{"service-dir":{"default":"sdk/documentintelligence"}},"emit":["@azure-tools/typespec-autorest"],"options":{"@azure-tools/typespec-autorest":{"azure-resource-provider-folder":"data-plane","emit-lro-options":"none","emitter-output-dir":"{project-root}/..","omit-unreachable-types":true,"output-file":"{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/DocumentIntelligence.json"},"@azure-tools/typespec-python":{"package-pprint-name":"Azure AI Document Intelligence","package-dir":"azure-ai-documentintelligence","package-name":"{package-dir}","package-version":"1.0.0b2","flavor":"azure","generate-test":true,"generate-sample":true},"@azure-tools/typespec-java":{"package-dir":"azure-ai-documentintelligence","namespace":"com.azure.ai.documentintelligence","enable-sync-stack":true,"custom-types-subpackage":"implementation.models","generate-tests":false,"customization-class":"customization/src/main/java/DocumentIntelligenceCustomizations.java","polling":{"buildDocumentModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"buildClassifier":{"final-type":"com.azure.ai.documentintelligence.models.DocumentClassifierDetails"},"composeModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"copyModelTo":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"}},"flavor":"azure"},"@azure-tools/typespec-csharp":{"package-dir":"Azure.AI.DocumentIntelligence","namespace":"Azure.AI.DocumentIntelligence","model-namespace":false,"flavor":"azure"},"@azure-tools/typespec-ts":{"title":"DocumentIntelligence","package-dir":"ai-document-intelligence-rest","generateMetadata":true,"generate-tests":false,"packageDetails":{"name":"@azure-rest/ai-document-intelligence","description":"Document Intelligence Rest Client","version":"1.0.0"},"flavor":"azure"}},"linter":{"extends":["@azure-tools/typespec-azure-rulesets/data-plane"]}},"emit":["@azure-tools/typespec-java"],"options":{"@azure-tools/typespec-autorest":{"azure-resource-provider-folder":"data-plane","emit-lro-options":"none","emitter-output-dir":"/mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence/TempTypeSpecFiles/DocumentIntelligence/..","omit-unreachable-types":true,"output-file":"data-plane/{service-name}/{version-status}/{version}/DocumentIntelligence.json"},"@azure-tools/typespec-python":{"package-pprint-name":"Azure AI Document Intelligence","package-dir":"azure-ai-documentintelligence","package-name":"azure-ai-documentintelligence","package-version":"1.0.0b2","flavor":"azure","generate-test":true,"generate-sample":true},"@azure-tools/typespec-java":{"package-dir":"azure-ai-documentintelligence","namespace":"com.azure.ai.documentintelligence","enable-sync-stack":true,"custom-types-subpackage":"implementation.models","generate-tests":false,"customization-class":"customization/src/main/java/DocumentIntelligenceCustomizations.java","polling":{"buildDocumentModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"buildClassifier":{"final-type":"com.azure.ai.documentintelligence.models.DocumentClassifierDetails"},"composeModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"copyModelTo":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"}},"flavor":"azure","emitter-output-dir":"/mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence"},"@azure-tools/typespec-csharp":{"package-dir":"Azure.AI.DocumentIntelligence","namespace":"Azure.AI.DocumentIntelligence","model-namespace":false,"flavor":"azure"},"@azure-tools/typespec-ts":{"title":"DocumentIntelligence","package-dir":"ai-document-intelligence-rest","generateMetadata":true,"generate-tests":false,"packageDetails":{"name":"@azure-rest/ai-document-intelligence","description":"Document Intelligence Rest Client","version":"1.0.0"},"flavor":"azure"}},"linterRuleSet":{"extends":["@azure-tools/typespec-azure-rulesets/data-plane"]}}
11:30:21.776 cmdout 	[Java-Sdk-Automation] [main] ERROR com.microsoft.typespec.http.client.generator.TypeSpecPlugin - Unable to complete customization
11:30:21.777 cmdout 	[Java-Sdk-Automation] java.lang.RuntimeException: java.lang.IllegalArgumentException: AnalyzeResultOperation does not exist in package com.azure.ai.documentintelligence.models
11:30:21.777 cmdout 	[Java-Sdk-Automation] 	at com.azure.autorest.customization.Customization.run(Customization.java:52)
11:30:21.777 cmdout 	[Java-Sdk-Automation] 	at com.microsoft.typespec.http.client.generator.core.postprocessor.Postprocessor.postProcess(Postprocessor.java:101)
11:30:21.777 cmdout 	[Java-Sdk-Automation] 	at com.microsoft.typespec.http.client.generator.Main.handleDPG(Main.java:146)
11:30:21.777 cmdout 	[Java-Sdk-Automation] 	at com.microsoft.typespec.http.client.generator.Main.main(Main.java:86)
11:30:21.777 cmdout 	[Java-Sdk-Automation] Caused by: java.lang.IllegalArgumentException: AnalyzeResultOperation does not exist in package com.azure.ai.documentintelligence.models
11:30:21.777 cmdout 	[Java-Sdk-Automation] 	at com.azure.autorest.customization.PackageCustomization.lambda$getClass$3(PackageCustomization.java:47)
11:30:21.778 cmdout 	[Java-Sdk-Automation] 	at com.azure.autorest.customization.implementation.Utils.returnIfPresentOrThrow(Utils.java:211)
11:30:21.778 cmdout 	[Java-Sdk-Automation] 	at com.azure.autorest.customization.PackageCustomization.getClass(PackageCustomization.java:45)
11:30:21.778 cmdout 	[Java-Sdk-Automation] 	at DocumentIntelligenceCustomizations.customizeAnalzyeResultOperation(DocumentIntelligenceCustomizations.java:30)
11:30:21.778 cmdout 	[Java-Sdk-Automation] 	at DocumentIntelligenceCustomizations.customize(DocumentIntelligenceCustomizations.java:22)
11:30:21.778 cmdout 	[Java-Sdk-Automation] 	at com.azure.autorest.customization.Customization.run(Customization.java:48)
11:30:21.778 cmdout 	[Java-Sdk-Automation] 	... 3 more
11:30:21.778 cmdout 	[Java-Sdk-Automation] [main] ERROR com.microsoft.typespec.http.client.generator.TypeSpecPlugin - Failed to complete postprocessing.
11:30:21.778 cmdout 	[Java-Sdk-Automation] java.lang.RuntimeException: Unable to complete customization
11:30:21.779 cmdout 	[Java-Sdk-Automation] 	at com.microsoft.typespec.http.client.generator.core.postprocessor.Postprocessor.postProcess(Postprocessor.java:104)
11:30:21.779 cmdout 	[Java-Sdk-Automation] 	at com.microsoft.typespec.http.client.generator.Main.handleDPG(Main.java:146)
11:30:21.779 cmdout 	[Java-Sdk-Automation] 	at com.microsoft.typespec.http.client.generator.Main.main(Main.java:86)
11:30:21.779 cmdout 	[Java-Sdk-Automation] Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: AnalyzeResultOperation does not exist in package com.azure.ai.documentintelligence.models
11:30:21.779 cmdout 	[Java-Sdk-Automation] 	at com.azure.autorest.customization.Customization.run(Customization.java:52)
11:30:21.779 cmdout 	[Java-Sdk-Automation] 	at com.microsoft.typespec.http.client.generator.core.postprocessor.Postprocessor.postProcess(Postprocessor.java:101)
11:30:21.779 cmdout 	[Java-Sdk-Automation] 	... 2 more
```

link: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4404510&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=200

section2:
```
07:58:46.000 cmdout 	[Java-Sdk-Automation] Resolved path: /mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence/TempTypeSpecFiles/node_modules/@typespec/compiler
07:58:46.193 cmdout 	[Java-Sdk-Automation] Compiling tsp using @azure-tools/typespec-java...
07:58:46.401 cmdout 	[Java-Sdk-Automation] Compiler options: {"outputDir":"/mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence","config":"/mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence/TempTypeSpecFiles/DocumentIntelligence/tspconfig.yaml","configFile":{"outputDir":"{cwd}/tsp-output","diagnostics":[],"projectRoot":"/mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence/TempTypeSpecFiles/DocumentIntelligence","file":{"kind":"yaml-script","file":{"text":"parameters:\n  \"service-dir\":\n    \"default\": \"sdk/documentintelligence\"\n\nemit:\n  - \"@azure-tools/typespec-autorest\"\n  # - \"@azure-tools/typespec-csharp\",\n  # - \"@azure-tools/typespec-python\",\n  # - \"@azure-tools/typespec-ts\"\nlinter:\n  extends:\n    - \"@azure-tools/typespec-azure-rulesets/data-plane\"\noptions:\n  \"@azure-tools/typespec-autorest\":\n    azure-resource-provider-folder: \"data-plane\"\n    emit-lro-options: \"none\"\n    emitter-output-dir: \"{project-root}/..\"\n    omit-unreachable-types: true\n    output-file: \"{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/DocumentIntelligence.json\"\n  \"@azure-tools/typespec-python\":\n    package-pprint-name: \"Azure AI Document Intelligence\"\n    package-dir: \"azure-ai-documentintelligence\"\n    package-name: \"{package-dir}\"\n    package-version: 1.0.0b2\n    flavor: azure\n    generate-test: true\n    generate-sample: true\n  \"@azure-tools/typespec-java\":\n    package-dir: \"azure-ai-documentintelligence\"\n    namespace: \"com.azure.ai.documentintelligence\"\n    enable-sync-stack: true\n    custom-types-subpackage: \"implementation.models\"\n    generate-tests: false\n    customization-class: customization/src/main/java/DocumentIntelligenceCustomizations.java\n    polling:\n      buildDocumentModel:\n        final-type: com.azure.ai.documentintelligence.models.DocumentModelDetails\n      buildClassifier:\n        final-type: com.azure.ai.documentintelligence.models.DocumentClassifierDetails\n      composeModel:\n        final-type: com.azure.ai.documentintelligence.models.DocumentModelDetails\n      copyModelTo:\n        final-type: com.azure.ai.documentintelligence.models.DocumentModelDetails\n    flavor: azure\n  \"@azure-tools/typespec-csharp\":\n    package-dir: \"Azure.AI.DocumentIntelligence\"\n    namespace: \"Azure.AI.DocumentIntelligence\"\n    model-namespace: false\n    flavor: azure\n  \"@azure-tools/typespec-ts\":\n    title: DocumentIntelligence\n    package-dir: \"ai-document-intelligence-rest\"\n    generateMetadata: true\n    generate-tests: false\n    packageDetails:\n      name: \"@azure-rest/ai-document-intelligence\"\n      description: \"Document Intelligence Rest Client\"\n      version: \"1.0.0\"\n    flavor: azure\n","path":"/mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence/TempTypeSpecFiles/DocumentIntelligence/tspconfig.yaml"},"value":{"parameters":{"service-dir":{"default":"sdk/documentintelligence"}},"emit":["@azure-tools/typespec-autorest"],"linter":{"extends":["@azure-tools/typespec-azure-rulesets/data-plane"]},"options":{"@azure-tools/typespec-autorest":{"azure-resource-provider-folder":"data-plane","emit-lro-options":"none","emitter-output-dir":"{project-root}/..","omit-unreachable-types":true,"output-file":"{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/DocumentIntelligence.json"},"@azure-tools/typespec-python":{"package-pprint-name":"Azure AI Document Intelligence","package-dir":"azure-ai-documentintelligence","package-name":"{package-dir}","package-version":"1.0.0b2","flavor":"azure","generate-test":true,"generate-sample":true},"@azure-tools/typespec-java":{"package-dir":"azure-ai-documentintelligence","namespace":"com.azure.ai.documentintelligence","enable-sync-stack":true,"custom-types-subpackage":"implementation.models","generate-tests":false,"customization-class":"customization/src/main/java/DocumentIntelligenceCustomizations.java","polling":{"buildDocumentModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"buildClassifier":{"final-type":"com.azure.ai.documentintelligence.models.DocumentClassifierDetails"},"composeModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"copyModelTo":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"}},"flavor":"azure"},"@azure-tools/typespec-csharp":{"package-dir":"Azure.AI.DocumentIntelligence","namespace":"Azure.AI.DocumentIntelligence","model-namespace":false,"flavor":"azure"},"@azure-tools/typespec-ts":{"title":"DocumentIntelligence","package-dir":"ai-document-intelligence-rest","generateMetadata":true,"generate-tests":false,"packageDetails":{"name":"@azure-rest/ai-document-intelligence","description":"Document Intelligence Rest Client","version":"1.0.0"},"flavor":"azure"}}},"doc":{"parameters":{"service-dir":{"default":"sdk/documentintelligence"}},"emit":["@azure-tools/typespec-autorest"],"linter":{"extends":["@azure-tools/typespec-azure-rulesets/data-plane"]},"options":{"@azure-tools/typespec-autorest":{"azure-resource-provider-folder":"data-plane","emit-lro-options":"none","emitter-output-dir":"{project-root}/..","omit-unreachable-types":true,"output-file":"{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/DocumentIntelligence.json"},"@azure-tools/typespec-python":{"package-pprint-name":"Azure AI Document Intelligence","package-dir":"azure-ai-documentintelligence","package-name":"{package-dir}","package-version":"1.0.0b2","flavor":"azure","generate-test":true,"generate-sample":true},"@azure-tools/typespec-java":{"package-dir":"azure-ai-documentintelligence","namespace":"com.azure.ai.documentintelligence","enable-sync-stack":true,"custom-types-subpackage":"implementation.models","generate-tests":false,"customization-class":"customization/src/main/java/DocumentIntelligenceCustomizations.java","polling":{"buildDocumentModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"buildClassifier":{"final-type":"com.azure.ai.documentintelligence.models.DocumentClassifierDetails"},"composeModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"copyModelTo":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"}},"flavor":"azure"},"@azure-tools/typespec-csharp":{"package-dir":"Azure.AI.DocumentIntelligence","namespace":"Azure.AI.DocumentIntelligence","model-namespace":false,"flavor":"azure"},"@azure-tools/typespec-ts":{"title":"DocumentIntelligence","package-dir":"ai-document-intelligence-rest","generateMetadata":true,"generate-tests":false,"packageDetails":{"name":"@azure-rest/ai-document-intelligence","description":"Document Intelligence Rest Client","version":"1.0.0"},"flavor":"azure"}}}},"filename":"/mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence/TempTypeSpecFiles/DocumentIntelligence/tspconfig.yaml","parameters":{"service-dir":{"default":"sdk/documentintelligence"}},"emit":["@azure-tools/typespec-autorest"],"options":{"@azure-tools/typespec-autorest":{"azure-resource-provider-folder":"data-plane","emit-lro-options":"none","emitter-output-dir":"{project-root}/..","omit-unreachable-types":true,"output-file":"{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/DocumentIntelligence.json"},"@azure-tools/typespec-python":{"package-pprint-name":"Azure AI Document Intelligence","package-dir":"azure-ai-documentintelligence","package-name":"{package-dir}","package-version":"1.0.0b2","flavor":"azure","generate-test":true,"generate-sample":true},"@azure-tools/typespec-java":{"package-dir":"azure-ai-documentintelligence","namespace":"com.azure.ai.documentintelligence","enable-sync-stack":true,"custom-types-subpackage":"implementation.models","generate-tests":false,"customization-class":"customization/src/main/java/DocumentIntelligenceCustomizations.java","polling":{"buildDocumentModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"buildClassifier":{"final-type":"com.azure.ai.documentintelligence.models.DocumentClassifierDetails"},"composeModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"copyModelTo":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"}},"flavor":"azure"},"@azure-tools/typespec-csharp":{"package-dir":"Azure.AI.DocumentIntelligence","namespace":"Azure.AI.DocumentIntelligence","model-namespace":false,"flavor":"azure"},"@azure-tools/typespec-ts":{"title":"DocumentIntelligence","package-dir":"ai-document-intelligence-rest","generateMetadata":true,"generate-tests":false,"packageDetails":{"name":"@azure-rest/ai-document-intelligence","description":"Document Intelligence Rest Client","version":"1.0.0"},"flavor":"azure"}},"linter":{"extends":["@azure-tools/typespec-azure-rulesets/data-plane"]}},"emit":["@azure-tools/typespec-java"],"options":{"@azure-tools/typespec-autorest":{"azure-resource-provider-folder":"data-plane","emit-lro-options":"none","emitter-output-dir":"/mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence/TempTypeSpecFiles/DocumentIntelligence/..","omit-unreachable-types":true,"output-file":"data-plane/{service-name}/{version-status}/{version}/DocumentIntelligence.json"},"@azure-tools/typespec-python":{"package-pprint-name":"Azure AI Document Intelligence","package-dir":"azure-ai-documentintelligence","package-name":"azure-ai-documentintelligence","package-version":"1.0.0b2","flavor":"azure","generate-test":true,"generate-sample":true},"@azure-tools/typespec-java":{"package-dir":"azure-ai-documentintelligence","namespace":"com.azure.ai.documentintelligence","enable-sync-stack":true,"custom-types-subpackage":"implementation.models","generate-tests":false,"customization-class":"customization/src/main/java/DocumentIntelligenceCustomizations.java","polling":{"buildDocumentModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"buildClassifier":{"final-type":"com.azure.ai.documentintelligence.models.DocumentClassifierDetails"},"composeModel":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"},"copyModelTo":{"final-type":"com.azure.ai.documentintelligence.models.DocumentModelDetails"}},"flavor":"azure","emitter-output-dir":"/mnt/vss/_work/1/s/azure-sdk-for-java/sdk/documentintelligence/azure-ai-documentintelligence"},"@azure-tools/typespec-csharp":{"package-dir":"Azure.AI.DocumentIntelligence","namespace":"Azure.AI.DocumentIntelligence","model-namespace":false,"flavor":"azure"},"@azure-tools/typespec-ts":{"title":"DocumentIntelligence","package-dir":"ai-document-intelligence-rest","generateMetadata":true,"generate-tests":false,"packageDetails":{"name":"@azure-rest/ai-document-intelligence","description":"Document Intelligence Rest Client","version":"1.0.0"},"flavor":"azure"}},"linterRuleSet":{"extends":["@azure-tools/typespec-azure-rulesets/data-plane"]}}
07:59:30.178 cmdout 	[Java-Sdk-Automation] [main] ERROR com.microsoft.typespec.http.client.generator.TypeSpecPlugin - Unable to complete customization
07:59:30.178 cmdout 	[Java-Sdk-Automation] java.lang.RuntimeException: java.lang.IllegalArgumentException: AnalyzeDocumentOptions does not exist in package com.azure.ai.documentintelligence.models
07:59:30.178 cmdout 	[Java-Sdk-Automation] 	at com.azure.autorest.customization.Customization.run(Customization.java:52)
07:59:30.178 cmdout 	[Java-Sdk-Automation] 	at com.microsoft.typespec.http.client.generator.core.postprocessor.Postprocessor.postProcess(Postprocessor.java:101)
07:59:30.178 cmdout 	[Java-Sdk-Automation] 	at com.microsoft.typespec.http.client.generator.Main.handleDPG(Main.java:146)
07:59:30.178 cmdout 	[Java-Sdk-Automation] 	at com.microsoft.typespec.http.client.generator.Main.main(Main.java:86)
07:59:30.179 cmdout 	[Java-Sdk-Automation] Caused by: java.lang.IllegalArgumentException: AnalyzeDocumentOptions does not exist in package com.azure.ai.documentintelligence.models
07:59:30.179 cmdout 	[Java-Sdk-Automation] 	at com.azure.autorest.customization.PackageCustomization.lambda$getClass$3(PackageCustomization.java:47)
07:59:30.179 cmdout 	[Java-Sdk-Automation] 	at com.azure.autorest.customization.implementation.Utils.returnIfPresentOrThrow(Utils.java:211)
07:59:30.179 cmdout 	[Java-Sdk-Automation] 	at com.azure.autorest.customization.PackageCustomization.getClass(PackageCustomization.java:45)
07:59:30.179 cmdout 	[Java-Sdk-Automation] 	at DocumentIntelligenceCustomizations.customizeAnalyzeDocumentOptions(DocumentIntelligenceCustomizations.java:137)
07:59:30.179 cmdout 	[Java-Sdk-Automation] 	at DocumentIntelligenceCustomizations.customize(DocumentIntelligenceCustomizations.java:36)
07:59:30.179 cmdout 	[Java-Sdk-Automation] 	at com.azure.autorest.customization.Customization.run(Customization.java:48)
07:59:30.179 cmdout 	[Java-Sdk-Automation] 	... 3 more
07:59:30.179 cmdout 	[Java-Sdk-Automation] [main] ERROR com.microsoft.typespec.http.client.generator.TypeSpecPlugin - Failed to complete postprocessing.
07:59:30.179 cmdout 	[Java-Sdk-Automation] java.lang.RuntimeException: Unable to complete customization
07:59:30.180 cmdout 	[Java-Sdk-Automation] 	at com.microsoft.typespec.http.client.generator.core.postprocessor.Postprocessor.postProcess(Postprocessor.java:104)
07:59:30.180 cmdout 	[Java-Sdk-Automation] 	at com.microsoft.typespec.http.client.generator.Main.handleDPG(Main.java:146)
07:59:30.180 cmdout 	[Java-Sdk-Automation] 	at com.microsoft.typespec.http.client.generator.Main.main(Main.java:86)
07:59:30.180 cmdout 	[Java-Sdk-Automation] Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: AnalyzeDocumentOptions does not exist in package com.azure.ai.documentintelligence.models
07:59:30.180 cmdout 	[Java-Sdk-Automation] 	at com.azure.autorest.customization.Customization.run(Customization.java:52)
07:59:30.180 cmdout 	[Java-Sdk-Automation] 	at com.microsoft.typespec.http.client.generator.core.postprocessor.Postprocessor.postProcess(Postprocessor.java:101)
07:59:30.180 cmdout 	[Java-Sdk-Automation] 	... 2 more
```

link: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4407262&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=194

**Comment by wanlwanl** [comment]
@XiaofeiCao  could you take a look at this one?

**Comment by wanlwanl** [comment]
@v-hongli1  could you take a look at this one?

**Comment by XiaofeiCao** [comment]
This is due to handwritten customization code. If generated code changes, customization code no-longer works.

**Comment by wanlwanl** [comment]
CC @jianingwang123 , no need to open this kind of case when you found "com.azure.autorest.customization.Customization.run", it indicates sdk automation is succeeded, and the failure is due to service team's custom code.
