### ISSUE TITLE
Issue warning instead of error when we cannot resolve queuing user

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#980]
Whenever there is a user we cannot resolve we get an error which causes some confusion about whether or not the publish succeeded or not. See https://dev.azure.com/azure-sdk/internal/_build/results?buildId=528578&view=logs&j=3e3661de-f7d0-5957-6723-798be5e1f473&t=42da0813-70a6-5e94-4c52-80d592e6d1d3 as an example.

```
:\a\1\s\tools_repo\tools\notification-configuration\identity-resolver\identity-resolver.csproj : warning NU1701: Package 'Microsoft.AspNet.WebApi.Core 5.2.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
D:\a\1\s\tools_repo\tools\notification-configuration\common\common.csproj : warning NU1701: Package 'Microsoft.AspNet.WebApi.Core 5.2.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project. [D:\a\1\s\tools_repo\tools\notification-configuration\identity-resolver\identity-resolver.csproj]
D:\a\1\s\tools_repo\tools\notification-configuration\identity-resolver\identity-resolver.csproj : warning NU1701: Package 'Microsoft.AspNet.WebApi.Core 5.2.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v2.1'. This package may not be fully compatible with your project.
D:\a\1\s\tools_repo\tools\notification-configuration\common\common.csproj : warning NU1701: Package 'Microsoft.AspNet.WebApi.Core 5.2.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
Helpers\***NameResolver.cs(70,35): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [D:\a\1\s\tools_repo\tools\notification-configuration\common\common.csproj]
Helpers\***NameResolver.cs(92,43): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. [D:\a\1\s\tools_repo\tools\notification-configuration\common\common.csproj]
Program.cs(13,30): warning CS1570: XML comment has badly formed XML -- 'An identifier was expected.' [D:\a\1\s\tools_repo\tools\notification-configuration\identity-resolver\identity-resolver.csproj]
Program.cs(13,30): warning CS1570: XML comment has badly formed XML -- 'The character(s) '-' cannot be used at this location.' [D:\a\1\s\tools_repo\tools\notification-configuration\identity-resolver\identity-resolver.csproj]
Program.cs(14,15): warning CS1570: XML comment has badly formed XML -- 'End tag 'summary' does not match the start tag ''.' [D:\a\1\s\tools_repo\tools\notification-configuration\identity-resolver\identity-resolver.csproj]
Program.cs(24,1): warning CS1570: XML comment has badly formed XML -- 'Expected an end tag for element 'summary'.' [D:\a\1\s\tools_repo\tools\notification-configuration\identity-resolver\identity-resolver.csproj]
warn: NotificationConfiguration.Helpers.***NameResolver[0]
      Could Not Resolve Identity of Name = Michael Yanni
Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at identity_resolver.Program.Main(String aadAppIdVar, String aadAppSecretVar, String aadTenantVar, String kustoUrlVar, String kustoDatabaseVar, String kustoTableVar, String identity, String targetvar) in D:\a\1\s\tools_repo\tools\notification-configuration\identity-resolver\Program.cs:line 67
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context) in /_/src/System.CommandLine/Invocation/CommandHandler.cs:line 147
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context) in /_/src/System.CommandLine/Invocation/ModelBindingCommandHandler.cs:line 60
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass2_0.<<InvokeAsync>b__0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationPipeline.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass1_0.<<ConfigureConsole>b__0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseErrorReporting>b__16_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 331
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass8_0.<<UseTypoCorrections>b__0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 225
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseSuggestDirective>b__7_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseParseDirective>b__6_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 177
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<UseHelp>b__14_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 299
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass3_0.<<UseVersionOption>b__0>d.MoveNext() in /_/src/System.CommandLine/Builder/CommandLineBuilderExtensions.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c.<<RegisterWithDotnetSuggest>b__17_0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 370
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.InvocationExtensions.<>c__DisplayClass5_0.<<UseExceptionHandler>b__0>d.MoveNext() in /_/src/System.CommandLine/Invocation/InvocationExtensions.cs:line 142
##[error]PowerShell exited with code '1'.

```
While the issue is embedded in this log, the log looks a little scary and it isn't clear if something broke or what happened. We should try to make this message a warning instead of an error, so we don't need to set continueOnError = true and we make it clearer what is happening. It might also worth adding an aka.ms link in the warning with more information about what folks should do to fix this issue. 

cc @scbedd

**Comment by kurtzeborn** [comment]
https://github.com/Azure/azure-sdk-tools/issues/1169 is related to this.  @mitchdenny has been investigating that one.

**Comment by chidozieononiwu** [comment]
The pipeline job has been refactored and that step removed.

**Comment by chidozieononiwu** [comment]
Seems this is still used in other repos
